### ISSUE TITLE
Additional Documentation - Connecting to External Id Server Blazor WebAssembly

### ISSUE THREAD

**Issue by benhysell** [dotnet/AspNetCore.Docs#17383] opened 2020-03-20 13:44 UTC
Scenario - Migrating from a React/Anglar/Vue/other frontend SPA backed by an asp.net core backend with a separate standalone Id Server and moving the front end to Blazor Web Assembly.

Desire - Continue to use that standalone Id Server with Blazor Web Assembly, would love to have more detailed documentation on configuring Blazor Web Assembly to communicate with that Id Server.

Details
Our current application is a React/Redux frontend backed by asp.net core backend and we have a separate Id Server already setup.  The front end uses the oidc-client-js for authentication.  My goal is to swap out the React/Redux with Blazor with minimum changes to our asp.net core backend to serve Blazor.

To do this we'll keep using the Id Server we already have, additionally our asp.net core backend is already configured to use jwt tokens passed from React/Redux and validated by the separate Id Server.  

Besides from making a few minor changes to serve Blazor I'm not changing the backend, however it isn't clear on how to configure Blazor to, optimistically, take in the current parameters I'm using to configure React/Redux for oidc-client-js and use them in Blazor.  Looking for more guidance / examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment] 2020-03-20 18:21
This looks like a dupe of https://github.com/dotnet/AspNetCore.Docs/issues/17288.
@guardrex if so, please close.

**Comment by guardrex** [comment] 2020-03-20 18:29
I added Javier's content on https://github.com/dotnet/AspNetCore.Docs/pull/17295/files, but it isn't specific ... just general advice.

**Comment by guardrex** [comment] 2020-03-20 18:31
... and Dan put up ...

**How to mix Blazor with apps that use existing frontend JS frameworks (Angular, React, etc.)** #12953

> Many customers have already built apps using existing frontend JS frameworks, like Angular, React, etc, but now want to start using Blazor in these apps. We should provide guidance on how to do this.

... but that's not the same thing as this.

**Comment by mkArtakMSFT** [comment] 2020-03-23 05:05
> 
> 
> I added Javier's content on https://github.com/dotnet/AspNetCore.Docs/pull/17295/files, but it isn't specific ... just general advice.

I think this is good alternative to this particular issue. We can close this one.
As for the one @danroth27 put together, that's slightly different and we need to have content to help existing non .NET customers to switch.

**Closed by mkArtakMSFT** 2020-03-23 05:05 UTC
Labels: Blazor, Source - Docs.ms, doc-idea

**Comment by benhysell** [comment] 2020-03-23 09:27
As of March 2020 if one is looking for a drop in Nuget Package and documentation on how to migrate an asp.net core backed, React/Angular/Vue frontend using oidc-client-js, connecting to IdentyServer to a Blazor front end still using that same asp.net core backend and IdentiyServer take a look at:

https://github.com/sounj142/HLSoft.BlazorWebAssembly.Authentication.OpenIdConnect

I was able to take their documentation and modify my Program.cs in my Blazor Client to connect to IdentityServer/the asp.net core backend with a few lines of configuration in the Blazor Client:

```
 public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("app");
        builder.Services.AddBaseAddressHttpClient();
        builder.Services.AddOptions()
            .AddAuthorizationCore()
            .AddBlazoredOpenIdConnect(options =>
            {
                options.Authority = "http://localhost:5000/";

                options.ClientId = "Client.Code";
                options.ResponseType = "code";

                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.Scope.Add("api");
            })
            .AddHttpClient<WeatherForecastService>(client =>
            {
                client.BaseAddress = new Uri("http://localhost:5001/");
            });
        await builder.Build().RunAsync();
    }
```
I'm hoping the Microsoft guidance / implementation / examples on this topic are this straight forward.
