### ISSUE TITLE
address CentOS: Host and deploy ASP.NET Core Blazor WebAssembly

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32728] opened 2024-06-04 00:15 UTC
### Description

See parent #32723
@guardrex  should I fix this and `@mention you` for review?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md

### Document ID

250e7458-3c1d-0117-261d-c03ac136f16a

### Article author

@guardrex

---
[Associated WorkItem - 261108](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261108)

**Comment by guardrex** [comment] 2024-06-04 04:39
I'll take care if it in the morning, but what's the fix fir EOL messaging? ... Are we removing all mention of CentOS (drop even the warning)?

**Comment by Rick-Anderson** [comment] 2024-06-04 05:39
> I'll take care if it in the morning, but what's the fix for EOL messaging? ... Are we removing all mention of CentOS (drop even the warning)?

I'd drop all mention of it. We don't want to mention an unsupported OS with no security updates.

**Comment by Rick-Anderson** [comment] 2024-06-04 05:57
@guardrex  if you can remember, can you `@mention` @Rick-Anderson  so I get email notication?  I filter out all gitHub emails ***except*** those with @Rick-Anderson  in the `to:` or `cc:`

<img width="299" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/929eed81-8917-4766-b553-04c4a58049b1">

**Comment by Rick-Anderson** [comment] 2024-06-04 06:11
@guardrex  wait until #32729 merges to avoid conflicts.

**Comment by guardrex** [comment] 2024-06-04 10:27
@Rick-Anderson ... Given the fix is total removal, you can add the Blazor EOL remarks if you want to your PR. I only said I'd take care of it because I thought we might be modifying the existing EOL language in some way.

The only Blazor mentions are in ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0

**Comment by guardrex** [comment] 2024-06-04 13:22
BTW @Rick-Anderson ... This is a duplicate of ...

https://github.com/dotnet/AspNetCore.Docs/issues/32308

... I needed to chat with Dan/Artak about our coverage before outright removing what we have, so I tracked it for .NET 9.

I'll ping Dan and Artak now on that other issue to see what they say.

**Comment by guardrex** [comment] 2024-06-04 22:38
I'm waiting to hear back on the other issue from Dan and Artak. After they advise, I get it squared away.

**Comment by guardrex** [comment] 2024-06-11 16:11
This was resolved by #32817.

**Closed by guardrex** 2024-06-11 16:11 UTC
Labels: Source - Docs.ms, Blazor, doc-bug, seQUESTered, aspnet-core/svc, blazor/subsvc
