### ISSUE TITLE
The sample does not work

### ISSUE THREAD

**Issue by smartprogrammer93** [dotnet/AspNetCore.Docs#21876] opened 2021-03-25 07:02 UTC
the sample provided in the following link does not work (js methods missing)

https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/BinarySubmit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2021-03-25 08:54
Duplicate of https://github.com/aspnet/samples/issues/65.

cc: @pranavkm

**Closed by guardrex** 2021-03-25 08:54 UTC
Labels: Blazor, Source - Docs.ms
