### ISSUE TITLE
Blazor VSC with C# Dev Kit coverage and review/update existing guidance

### ISSUE THREAD

**Issue by wgrs** [dotnet/AspNetCore.Docs#30170] opened 2023-08-28 10:41 UTC
Why is it that so many asp.net instruction documents are written so badly? In most cases they are no help at all. This holds true even more so when following Linux instructions on .net. Debugging on vscode on Linux is the same. You are almost guaranteed to fail using the Microsoft documentation and have to try and find help on other forums. 

EDIT by guardrex ... ***NOTE TO SELF*** .... https://github.com/dotnet/AspNetCore.Docs/pull/30363#issuecomment-1720139468

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2023-08-28 11:05
Hello @wgrs ... I'm not sure if you're only referring to Linux/VS Code or not. Can you clarify?

Reports of 'this doesn't work' usually aren't specific enough for us to take action on ...

* What doesn't work? What errors are you seeing or what behaviors are failing? 
* Which section (or sections) are you referring to (and note that the Linux config guidance in [the tooling article](https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-7.0&pivots=linux) must be followed, as this guidance states)?
* What flavor of Linux are you using? 
* What version of .NET are you using?
* What browser are you using?

We usually need a more complete report in order to proceed. However, we can schedule this issue for a complete review of the Linux with VSC coverage, including the Linux guidance in the Tooling article. That sounds like a good idea anyway at this point because a few years have passed since we've reviewed the content. Every few years, we try to overhaul and update every document, and I think it is time for this article.

We're slammed at the moment with .NET 8 work, but we'll try to get to this issue as soon as we can. I suspect it will be reached in 24Q1. That's the soonest that I'd be free to work on it, unless we can determine a more specific problem that I can address right now. Please provide any additional information that you can.

**Comment by wgrs** [comment] 2023-08-28 11:31
Thanks for the speedy response. I have been trying to get debugging working in vscode on a Blazor wasm project.  I have followed all the instructions on the [https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio](url) page. The breakpoints are not being loaded. Of course, the C# Dev Kit is throwing loads of errors but that seems to be par for the course. I am not sure if that is affecting the debugging.

**Comment by guardrex** [comment] 2023-08-28 11:36
Thanks for the extra information. Safia on the product unit used to handle the WASM debugging experience, but she might not be handling it any longer. I emailed to ask if she's still working this set of features or if she knew who was. We might end up informing Artak, who will assign a product unit engineer to help ... he might even move this entire issue over to the product unit's repository for work and tracking. Sometimes, the problem isn't in the documentation ... it's a bonafide ***bug*** 😈 that's cropped up that must be addressed. Stand-by while we find out how to triage this. I think we'll have some action by the EOD.

**Comment by guardrex** [comment] 2023-08-28 14:38
I spoke with Safia ... *Indeed!* I just barely remembered that she doesn't work on the Blazor WASM debug (or anything for Blazor really) at this point. Let me ping Artak to see how we'll triage this.

I'll note here one interesting remark that she made ...

> As for this particular issue, it might be helpful to have the CTI team do a test of VS Code debugging + Linux + C# Dev Kit to identify any issues with that particular combination.

... which means that you might be hitting some real tooling/framework problems, perhaps outside of documentation or perhaps that will also need documentation updates.

*Stand-by* ......... I'll email Artak now.

**Comment by guardrex** [comment] 2023-08-29 15:37
No response yet. They're buried in work for .NET 8 at the moment 😅. This is crunch time for the release, which is due out in November, and there's still a lot of work to do AFAICT from my vantage point.

If we don't hear back by tomorrow (Wednesday), we'll close this issue in favor of a product unit issue on their repo. I'll ping u back here tomorrow with what to do to set that issue up.

**Comment by wgrs** [comment] 2023-08-29 15:40
Thanks for the update

**Comment by guardrex** [comment] 2023-08-31 16:33
They're buried in work. Open a support request on their repo for assistance ...

https://github.com/dotnet/aspnetcore/issues

Notes for the issue ...

* Provide the specifics as you stated in your latter comment above at https://github.com/dotnet/AspNetCore.Docs/issues/30170#issuecomment-1695532330. They need the details on your environment, versions, and exact behaviors (break points not being hit).

* It's probably a good idea to mention in passing that Safia said in the doc issue discussion ...

  > As for this particular issue, it might be helpful to have the CTI team do a test of VS Code debugging + Linux + C# Dev Kit to identify any issues with that particular combination.

  ***BUT*** ... don't ping her using her GH handle. She doesn't work on Blazor now. She used to work on the WASM debugging experience, and her remark is a valuable bit of insight. If they want to discuss it with her, they'll ping her if they need to.

* Add the following line to the end of your opening issue comment to cross-link this issue to the new issue over there ...

  ```
  cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30170
  ```

  ... I'll re-open this issue for doc work if it turns out that we are missing some information or if there was a change that I'm not aware of.

* WRT the timing of their investigation, they're swamped with .NET 8 work and have a hard deadline to get issues resolved prior to the .NET 8 release target in November. I'm just letting you know in case it takes them a little while to investigate.

I'll close this now and keep an eye 👁️ on your PU issue.

**Comment by guardrex** [comment] 2023-09-01 22:58
BTW ... I noticed some issues pertaining to Blazor and C# Dev Kit ...

https://github.com/microsoft/vscode-dotnettools/issues?q=is%3Aissue+blazor+is%3Aopen

... but not necessarily breakpoints not being hit. I wonder if that would be a better spot to open than the PU's repo over here? If you open it for the PU tho, that's fine ... they'll move the issue over there if they think it's a C# Dev Kit-related problem.

**Comment by wgrs** [comment] 2023-09-02 08:33
To be fair - there is so much wrong with C# Dev Kit / vscode , it hard to know which is the cause - does the C# Dev Kit debugging settings override the built in vscode debugger? Does the C# Dev Kit replace the debugging in vscode? I have no idea and there is zero documentation. Opening Dev Kit settings is also no help. This is beyond frustrating. I don't understand how something as completely non functioning as the dev kit can even be rolled out.

**Comment by guardrex** [comment] 2023-09-02 10:52
I ping @danroth27 and @mkArtakMSFT so that they can see your feedback.

I'm going to re-title and use this issue to track any work that they would like done for VSC + C# Dev Kit. I know it's a paid product for professional/commercial use, which might limit the extent that documentation suggests that developers use it over the current guidance that doesn't pitch its use.

As for what it uses and how it works, I don't know if the C# Dev Kit uses the **Blazor WASM Debugging Extension** or not. I haven't researched C# Dev Kit debugging for Blazor (*yet* ... I plan to), and the entire subject of what to cover here on the C# Dev Kit is only coming up per our discussion about it. We'll find out the plan for coverage as soon as I hear back from Dan and Artak on it.

My guess is that the C# Dev Kit repo issues are the best place to open an issue for that team to take a look at what you're seeing if it looks like the tooling is to blame, which seems likely to me ...

https://github.com/microsoft/vscode-dotnettools/issues

Describe your environment and list the versions of everything. Paste in errors/warnings/screenshots that might be helpful to them.

I still think cross-linking this issue makes sense so that I can follow along and see what they find out. You can paste this into the opening comment of your issue ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30170
```

I'm buried in work right now for .NET 8, so I won't reach this for several weeks unless there's something fast that I can do to improve the article now. I'll be :ear: on your product unit issue.

**Comment by wgrs** [comment] 2023-09-02 11:02
Thank you. I am attempting to follow the Debugging Wasm document again. There are a range of configuration errors and warnings being thrown that aren't referenced in the document. So not bugs per se but it's preventing progress none the less.

**Comment by guardrex** [comment] 2023-09-02 11:10
... and a complete review of the existing guidance is still in order because it has been a few years since it went up. Periodic overhauls almost always lead to much better guidance.

**Comment by guardrex** [comment] 2023-09-11 18:47
Additional update from the product unit. They said (offline) ...

> I have just tested it and it's working. We need to create a BlazorWasm app, open it on VSCode with C# DevKit installed, open a *.cs or a *.razor file, and press f5 and choose C# debugger.
We don't need to create any launch.json file, it's just press f5 and we can add breakpoints on Counter.razor and pause on it.

I'll confirm it myself when I reach this article for updates, hopefully before 8.0 reaches RTM in November.

**Comment by guardrex** [comment] 2023-09-14 20:57
***NOTE TO SELF*** ...... https://github.com/dotnet/AspNetCore.Docs/pull/30363#issuecomment-1720139468

**Closed** 2023-09-22 15:17 UTC
Labels: Pri1, Source - Docs.ms, Blazor, doc-enhancement, support-request, 8.0
