### ISSUE TITLE
Missing SignalR config?

### ISSUE THREAD

**Issue by LucaGabi** [dotnet/AspNetCore.Docs#11403] opened 2019-03-14 08:33 UTC
Is there nothing to configure for SignalR to work behing a ngnix reverse proxi ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by dustout** [comment] 2019-03-31 05:51
I ran into the same issue. Adding the below location to nginx where /dataHub is the name of your hub should do the trick. 

```
location /dataHub {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        #proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

**Comment by davidfowl** [comment] 2019-03-31 06:57
cc @anurse @bradygaster this seems important

**Comment by BrennanConroy** [comment] 2019-03-31 07:47
Similar to/dupe of https://github.com/aspnet/Docs/issues/10827

**Comment by guardrex** [comment] 2020-03-10 12:33
Note to the content author: We have some movement on this subject for SignalR+WebSockets on Linux at https://github.com/dotnet/AspNetCore.Docs/pull/17181, but that's only a partial solution because it only directly addresses the subject in the Blazor topic.

That's a community generated PR, so it might be best to wait until that goes in and then perform some followup work. After that one is merged, I recommend moving the content to the Linux topics (per this issue) and cross-link to it from SignalR and Blazor topics.

**Comment by Rick-Anderson** [comment] 2020-04-10 17:46
Moved to Master issue: Host ASP.NET Core on Linux with Nginx #17735

**Comment by guardrex** [comment] 2020-07-17 13:06
Let's close because https://github.com/dotnet/AspNetCore.Docs/issues/10827 can handle the updates. I'll leave a comment there to cross-link the new coverage from the Linux Nginx topic.

**Closed by guardrex** 2020-07-17 13:06 UTC
Labels: P2, SignalR, Source - Docs.ms, doc-enhancement
