### ISSUE TITLE
Document the difference between web, mvc, webapp, webapi, gRPC, and razor and when to use which

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/AspNetCore.Docs#17882] opened 2020-04-17 19:26 UTC
Right now when I need to create a new website what should I choose? The templates look similar but with some differences. I think this should be documented with some good guidance for beginners.

***EDIT by @Rick-Anderson*** per @danroth27 

> Given the options for ASP.NET Core 3.0 currently available in Preview 4, it looks like the **Web app TOC node** could use a new Overview topic that also helps you quickly narrow down what pattern/set of features to consider to meet a common web app goal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by KirillOsenkov** [comment] 2020-04-17 20:28
I think the section that lists `dotnet new mvc` and `dotnet new webapp` should have a link to https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio, which explains the difference between MVC and Razor pages.

**Comment by TimmyGunawan123** [comment] 2020-05-19 11:46
> Right now when I need to create a new website what should I choose? The templates look similar but with some differences. I think this should be documented with some good guidance for beginners.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
> * Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
> * Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
> * Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
> * Product: **dotnet-core**
> * Technology: **dotnet-cli**
> * GitHub Login: @tdykstra
> * Microsoft Alias: **tdykstra**

Im still confusing on this one, maybe try this one http://www.858airsoft.com/

**Comment by mkArtakMSFT** [comment] 2020-11-18 18:04
@danroth27, @LadyNaggaga can you guys help with this please? Thanks!

**Comment by Rick-Anderson** [comment] 2021-01-12 22:58
> @danroth27, @LadyNaggaga can you guys help with this please? Thanks!

**Comment by danroth27** [comment] 2021-01-12 23:29
Yup, I'll be drafting content for this, hopefully in the next few weeks.

**Comment by rupalivohra** [comment] 2021-02-23 06:38
Hey @danroth27 - were you able to get some more discerning documentation drafted?

**Comment by wadepickett** [comment] 2021-05-20 23:06
@danroth27, I have a open window of time to work on this now.  Do you happen to have a draft going we can work on together?

**Comment by wadepickett** [comment] 2021-05-20 23:11
@scottaddie and @danroth27, and @Rick-Anderson ,

The new aspnetcore.docs issues created for this seem to imply  two documents:  An overview and a decision tree on when to use what.  I would think this could be one combined doc.  I would think a good overview that would explain when to use what.  Any objections to one topic rather than two?

**Comment by Rick-Anderson** [comment] 2021-05-20 23:55
Make sure you record it.

**Comment by wadepickett** [comment] 2021-07-06 19:03
Closing this as a duplicate of #21821.  

Also, rather then doing both an overview and a decision tree type topic, after discussion with danroth27 it was decided a single new "decision tree" topic would handle this.  Thanks everyone for the suggestions and feedback.

**Closed by wadepickett** 2021-07-06 19:03 UTC
Labels: P0, PU, RR, Source - Docs.ms
