### ISSUE TITLE
How can it return 401 code,not redirect to login page?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17931] opened 2020-04-20 20:32 UTC
@717009629 commented on [Fri Apr 17 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/260)

How can it return 401 code,not redirect to login page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
---

@srvbpigh commented on [Sat Apr 18 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/260#issuecomment-615546178)

Hello, @717009629
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment] 2020-04-20 20:40
Duplicate of #16726

**Closed by Rick-Anderson** 2020-04-20 20:40 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
