### ISSUE TITLE
IStringLocalizer is unable to locate resource in Linux environment

### ISSUE THREAD

**Issue by gkarnik-gl** [dotnet/AspNetCore.Docs#22979] opened 2021-08-08 16:21 UTC
I'm experiencing a issue where localization in aspnetcore WebApi solution using IStringLocalizer doesn't work in Linux environment i.e. ResourceNotFound:true whereas it seems to work fine in Windows environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#resource-file-naming)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-08-08 16:31
We know it works on Linux. Where are the resources on Linux?

**Comment by gkarnik-gl** [comment] 2021-08-08 16:38
It's a Azure App Service (Linux Plan) environment. Without setting LocalizationOptions.ResourcesPath nor the AssemblyInfo.cs for RootNamespace and ResourceLocation attributes, it works fine while debugging and while deployed to IIS on a Windows 10 pro machine but not on App Service Linux Plan.

**Comment by Rick-Anderson** [comment] 2021-08-18 23:58
@hishambinateya can you help?

**Comment by hishamco** [comment] 2021-08-19 18:45
It should work on both, unfortunetaly I can't test this one because I have a Windows OS only

**Comment by hishamco** [comment] 2021-08-19 18:46
BTW the Linux is case sensitive be sure about the casing on non Windows OSs

**Comment by Rick-Anderson** [comment] 2021-08-19 19:48
@gkarnik-gl  can you create the simplest possible app that reproduces the problem on Azure Linux and fails on Azure Windows? Provide a GitHub link to your sample.

**Comment by Ponant** [comment] 2021-08-20 05:01
@gkarnik-gl , I have no idea on Linux, which .Net version are you running?

**Comment by gkarnik-gl** [comment] 2021-08-20 05:03
@Ponant - The app is running on .NET 5.0

**Comment by juandrn** [comment] 2021-11-22 23:50
Same problem here, IStringLocalizer works in windows environments (development), but in alpine container doesn't work, I've configured it with AcceptLanguageHeaderRequestCultureProvider, and I test it changing order of lang setting order in chrome 

![image](https://user-images.githubusercontent.com/13983901/142951619-e22aa699-5b1a-41d5-b676-b2a85b552671.png)

In the request header show "Accept-Language: es-ES,es;q=0.9,en;q=0.8"
But always select "en"

I have two resource files
- Resources.es.resx
- Resources.resx

Best regards

**Comment by hishamco** [comment] 2021-11-23 05:50
@juandrn please show us the localization setup in `Startup`

**Comment by juandrn** [comment] 2021-11-23 12:33
@hishamco no problem



` 
//Configure service
            services.Configure<RequestLocalizationOptions>(opts =>
            {
                opts.DefaultRequestCulture = new RequestCulture("en");
                // Formatting numbers, dates, etc.
                opts.SupportedCultures = DMC.Manager.Helper.CultureHelper.Cultures;
                // UI strings that we have localized.
                opts.SupportedUICultures = DMC.Manager.Helper.CultureHelper.Cultures;

                opts.AddInitialRequestCultureProvider(new AcceptLanguageHeaderRequestCultureProvider());
            });
            services.AddLocalization();
//...
//...
`

`
//Configure
            var options = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
            app.UseRequestLocalization(options.Value);
`

**Comment by hishamco** [comment] 2021-11-23 13:03
Try to move your `es` first or remove `English` from the browser languages

**Comment by juandrn** [comment] 2021-11-23 23:20
@hishamco I've changed it and works 👍 ( :O ) 

```csharp
             var cultures = new List<CultureInfo> {
                     new CultureInfo("es")   //Now first
                     new CultureInfo("en"),  // 
               };
```

**Comment by hishamco** [comment] 2021-11-24 07:46
The issue is your header contains 'en' which is declared as default culture. FYI the question is not related to specific OS, @Rick-Anderson we can close this now

**Comment by hishamco** [comment] 2021-11-24 07:47
The issue is your header contains 'en' which is declared as default culture. FYI the question is not related to specific OS, @Rick-Anderson we can close this now

**Closed** 2021-11-24 16:28 UTC
Labels: Source - Docs.ms, needs-more-info
