### ISSUE TITLE
How to customize the layout used by Identity pages?

### ISSUE THREAD

**Issue by lucent-sea** [dotnet/AspNetCore.Docs#18358] opened 2020-05-17 19:19 UTC
I'd like to customize the navbar and footer used in Identity pages (e.g. https://localhost:5001/Identity/Account/Register).

Where is the markup located?  In Razor Pages projects, it was located in /Pages/Shared/_Layout.cshtml.  I cant find it now.

I tried to import scaffolded item Account/Manage/Layout, but then I get an error: InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Scripts'.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-05-17 19:41
Hello @lucent-sea ... this is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/15651.

I'm proposing *some* information on customizing the default Identity UI to match Blazor's theme on the PR at ... https://github.com/dotnet/AspNetCore.Docs/pull/17940. You can take a look at the diff to see what I'm pitching.

It's not going to be a complete styling reference tho ... you'll still likely need to do additional styling work beyond what the PR shows. That's just to get devs going with it.

**Closed by guardrex** 2020-05-17 19:41 UTC
Labels: :watch: Not Triaged, Blazor, Source - Docs.ms
