### ISSUE TITLE
Firefox does not trust self-signed certificates (dot net core development)

### ISSUE THREAD

**Issue by jaoord** [dotnet/AspNetCore.Docs#20349] opened 2020-10-29 09:47 UTC
Even after cleaning old certificates and creating new certificates and restarting the browser, Firefox will not trust the localhost development certificate:

![image](https://user-images.githubusercontent.com/6464609/97552089-1a4dce80-19d4-11eb-9d54-9a794a078945.png)

How can we run a localhost dotnet development project in Firefox?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/nl-nl/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2020-10-29 20:58
Please transfer this to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by Rick-Anderson** [comment] 2020-10-29 21:03
@jaoord  see https://github.com/dotnet/AspNetCore.Docs/pull/20356

**Comment by guardrex** [comment] 2020-10-29 23:13
@jaoord ... I use FF, including 5.0 preview, and I'm not seeing any cert errors.

We probably can't provide product support here for that, so you can open an issue for the product unit to see if they want to investigate the cause. Before doing that tho, I recommend that you search the Net, particularly [SO](https://stackoverflow.com/), first just to make sure that someone hasn't already called it out and figured out the cause. Then ... open an issue here ...

https://github.com/dotnet/aspnetcore/issues

If you do find out what's causing it and think that docs need to mention a *gotcha*, then you can post back on this issue (or open a new one) with what you find out.

@Rick-Anderson I recommend that closing this for now until more information is available.

**Closed** 2020-10-29 23:22 UTC
Labels: Source - Docs.ms, doc-bug

**Comment by jaoord** [comment] 2020-10-30 08:12
As mentioned in the other issue (#20356) the solution is to go to **about:config** in Firefox and set **security.enterprise_roots.enabled** to **true**.

**Comment by guardrex** [comment] 2020-10-30 11:47
Very good ... glad it had a happy ending. That's the default for that setting, so I don't think we need doc coverage. Thanks for letting us know how it turned out.
