### ISSUE TITLE
policy based or claim based on pure web assembly client

### ISSUE THREAD

**Issue by AlexSapple** [dotnet/AspNetCore.Docs#17633] opened 2020-04-06 21:26 UTC
Hi,
(experimenting with blazor - new to it, and looking to see if I can migrate an existing site to blazor)
this page is great and really helpful! - but is there any info or details on implementing policy based authorisation when you are in a purely client based app. So, where you don't have the startup.cs to define policies? (can they be defined somewhere in a client app?)

If using just claims instead (which I can happily extract in a purely client based scenario without issue) - then is seems that the AuthorizeView (wonderful as it is) - only accepts a policy (instead of a required claim). If the authorize view could accept a collection of required claims - then I could still use the that component to achieve something similar to a policy (if not then I think I need to create either a custom component)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-04-06 21:42
Hello @AlexSapple ... *Yes!* ... and I've actually been working all day today on new guidance for part of that scenario.

I'm going to put up an issue tomorrow with many details about using Azure AD `groups` and `roles` claims for authz in Blazor WebAssembly apps (both standalone and the hosted types).

I'll leave your email in my Inbox and then ping you tomorrow on the issue that I put up. The issue is going to be for discussion with management on what and where we'll be covering the concepts (and *even if I'm doing it right!* :smile:).

Suffice to say here for now ... yes, you can add policies ... like this :point_down:

```csharp
builder.Services.AddAuthorizationCore(options =>
{
    options.AddPolicy("CustomPolicy", policy => policy.RequireClaim("groups", "213b6935-a839-49e8-86e0-acc7d1cd1582"));
});
```

... in `Program.Main`. That one that I just put there shows how to use a security `groups` claim from Azure AD (a custom group created for an app) that comes down when the manifest is updated to `groupMembershipClaims` is set to `SecurityGroup`. Anyway ... that's just a tidbit ... I'll have a lot more detail and examples on the issue for discussion tomorrow.

I'm going to close this, but I will ping u tomorrow. I'm sure you'll find my post tomorrow afternoon helpful, especially if you're going to be doing anything with Azure AD and Blazor WebAssembly. Caveat tho: I do need engineering to look it over and make sure that I'm not creating any **_code smells_** 👃 ... actually ... when it comes to security, I sometimes create more of a :poop: **_code STINK_** :poop: 😵 ... We'll see soon enough!

**Closed by guardrex** 2020-04-06 21:42 UTC
Labels: :watch: Not Triaged, Blazor, Source - Docs.ms

**Comment by AlexSapple** [comment] 2020-04-07 06:20
Thanks so much,

that's brilliant - and really appreciated the quick reply and detailed answer!! - really great :)

regards,
Alex.

________________________________
