### ISSUE TITLE
How to properly destroy javascript component and avoid JSDisconnectedException

### ISSUE THREAD

**Issue by Liero** [dotnet/AspNetCore.Docs#27094] opened 2022-09-26 09:36 UTC
My blazor component wraps existing javascript component that needs some javascript cleaning when removed from DOM.

I call `jsObjectRef.InvokeVoidAsync("destroy")` when disposing blazor component, but it throws unhandled exception:

 >     Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.

The logs are then bloated with this exception

```csharp
    public class RichTextEditor : InputTextArea, IAsyncDisposable
    {
        ElementReference? _elementRef;
        IJSObjectReference? _jsObjectRef;

        [Inject] IJSRuntime Js { get; set; } = default!;

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                _jsObjectRef = await Js.InvokeAsync<IJSObjectReference>("CKEditorInterop.init", _elementRef;
            }
            await base.OnAfterRenderAsync(firstRender);
        }

        public async ValueTask DisposeAsync()
        {
            if (_jsObjectRef != null)
            {
                await _jsObjectRef.InvokeVoidAsync("destroy"); //this throws JSDisconnectedException when browser is reloaded  or closed or disconnected
                await _jsObjectRef.DisposeAsync();
            }
        }
    }
````

Is it possible to avoid this exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ea38a-649b-303d-bebf-c701e216ba25
* Version Independent ID: 9e197a8b-2616-8363-0a15-38cac802e82e
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-09-26 09:48
Good ❓, @Liero ... Open an issue with the product unit ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27094
```

... to the bottom of your opening comment so that I can follow along. I'll probably re-open this for doc work depending on what they say.

**Comment by Liero** [comment] 2022-09-28 08:11
@guardrex: Imo, the documentation should be updated with JSDisconnectedException whenever an jsinterop is invoked from Dispose method, including IJSObjectReferece.DisposeAsync():

```csharp
async ValueTask IAsyncDisposable.DisposeAsync()
{
   try 
   {
      if (mapInstance is not null)
      {
          await mapInstance.DisposeAsync();
      }

      if (mapModule is not null)
      {
          await mapModule.DisposeAsync();
      }
    }
    catch (JSDisconnectedException)
    {
    }
}
` ``

**Comment by guardrex** [comment] 2022-10-12 14:04
@Liero ... Let's discuss further here for a bit, then I'm going to let my other tracking issue track this for further docs work.

> The docs doesn't mention JSDisconnectedException at all

It wasn't deemed significant enough to mention in the past. I just added it to a tracking issue. I anticipate that I'll be able to address it in the next couple of weeks.

> when browser is refreshed (circuit disconnected) in Blazor Server app - it throws unhandled exception when disposing - should it be handled or ignored?

"Handled" is the answer. We cover it, but it isn't cross-linked in the JS intorop node (*yet*). I'll work on that for the doc updates. I'll also explore this further in disposal coverage for calling into .NET (the other JS interop topic) and react in both docs as needed.

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0#component-disposal

WRT the memory leak piece ...

When circuit fails (for this or any other reason), framework-based, automatic GC occurs for the old circuit. I wouldn't be surprised to learn that some .NET GC things happen outside of Blazor in some circumstances ✨. I cover the level of detail that the PU wishes to cover on these aspects. Thus far, they haven't advised me to document things further than what we have in the docs, perhaps partially because the GC aspects are considered internal to the framework, subject to change without notice, and not particularly relevant in most Blazor app development scenarios. True tho, that they do want memory leak concerns covered. I remain with an 👂 open on it, and I'll consult with the PU for the doc updates when I reach them on the other tracking issue.

What the PU has been focusing on are the **_fatal circuit situations_** 💀⚰️, as I'll mention further in a moment 👇.

> I still don't know whether IJSObjectReference should be disposed in Blazor ... when I dispose it manually in JavaScript as @javiercn suggested

I think 'no' based on the feedback if you dispose it on the JS side. However, WRT the whole suggestion ...

> alternative cleanup mechanism directly on the JS side (for example, using the MutationObserver)'

Correct ... we don't cover that at all. I took a look to see where/how this has come up over the years ...

https://github.com/dotnet/aspnetcore/search?q=MutationObserver&type=issues

... and there are some interesting mentions and code examples in some of those issues. However, I have no direction from the PU on covering `MutationObserver` for any particular purpose. The PU would need to supply something more concrete to me to cover, *if they want it covered at all*. Thus far, it seemed to be considered too *weedy-ish* 😄, but they could change their mind when I speak further with them about the doc updates.

> In the Mapbox sample, the mapModule stays undisposed:

... and ...

> according to the docs, the code above causes memory leak on the server since the IJSObjectReference won't be garbage collected

*Indeed!* ... and it doesn't matter the order. It will 💥 there with that exception for either disposal call.

AFAIK, the 💀 circuit cleanup by the framework doesn't let a memory leak occur (or GC behavior outside of Blazor doesn't let that occur). I need to change the wording of that remark so that the reader doesn't jump to that conclusion. That's tracked by my docs issue now, so I'll work on that with the PU's help.

**_HOWEVER_**, we're missing an important cross-link to the error handling coverage for JS interop. It was just an oversight at the time, and I'll get the proper cross-links in there on the doc updates ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0#javascript-interop

Note that the section does **not** address the `JSDisconnectedException` unhandled exception situation that we're discussing here. We just say that **any** unhandled exception is fatal to a circuit when disposing.

I think we do need a bit on `JSDisconnectedException` with the cross-linking. In this case, we know that it's fatal to close the browser/browser window/browser tab. Steve is implying via his code that he'll just let the Blazor framework clean those objects up along with everything else that it does behind the scenes.

What I wonder is in cases where `JSDisconnectedException` is thrown for some other reason that kills the circuit outside of a normal user action based on normal user behavior (e.g., closing the tab) that's a normal circuit-killing user gesture. We only discuss 'trapping and logging' on your own. We don't get into any details about that trapping and logging; and as you see, we don't get into it for the JS calls case (including disposal). When I reach my tracking issue entry for work, I'll need to investigate and chat with the engineers further about what to say in the doc.

WRT reacting to it with an example update, Steve didn't feel like it should be addressed *at the time*. It could be addressed tho by following the guidance we currently provide. I think we can trap in there and log it out on our own. It would be handled and logged. The circuit fails anyway ... for that case ... closing the tab/window ... but we avoid the unhandled exception.

```csharp
async ValueTask IAsyncDisposable.DisposeAsync()
{
    try
    {
        if (mapInstance is not null)
        {
            await mapInstance.DisposeAsync();
        }

        if (mapModule is not null)
        {
            await mapModule.DisposeAsync();
        }
    }
    catch (JSDisconnectedException ex)
    {
            // log ex.Message here
    }
}
```

**Comment by Liero** [comment] 2022-10-14 08:28
So in conclusion:

1. JSObjectReference can be disposed on either JS or Server side
2. Not disposing on server does not cause memoryleak outside the circuit -> when circuit is destroyed, all JSObjectReference are collected by GC anyway.
3. Add try catch to avoid logging, but it will swallow exceptions when the circuit is disconnected for other reasons what user ending the session

**Comment by guardrex** [comment] 2022-10-14 08:46
Yes, I think that's right.

On item 2, they've implied that the most efficient practice is for components to dispose a `JSObjectReference` in developer code (or client-side). If the circuit fails tho ... as you reported and I was able to reproduce here ... I now see that it can't be disposed server-side. The circuit is in the process of being destroyed by the framework. As far as I know, the circuit disposal will either dispose of the `JSObjectReference` or the .NET GC will dispose it later. This aspect was never communicated to me for the documentation, but it will need to be addressed. I think we will end up trapping and logging `JSDisconnectedException` in all of the examples that dispose `JSObjectReference`.

I thought that I'd work this from the other tracking issue, but I'm going to just leave this issue open and work it from here. I think that I'll have time early next week to work on this. I just have a couple of .NET 7 items that I need to resolve first.

Whatever I come up with, I'll ping Steve on the PR to have him look things over and both catch any mistakes that I make but also provide any additional guidance that he thinks devs should know.

Leave this issue open. It will close when the PR eventually merges.

**Comment by Liero** [comment] 2022-10-15 11:07
@guardrex: Thanks. I think this will help the community. I've seen this exception in logs far too often even in commercial 3rd party components year or two ago, before they had to figure out this by themselves

It would maybe help to briefly explain how the mechanism behind the `JSObjectReference` works. Does the JS client tracks all JSObjectReferences, until they are disposed? Does the server (or webassembly)? 

Actually, the same questions are valid for `DotNetObjectReference` as well.

**Comment by guardrex** [comment] 2022-10-15 11:11
Good idea ... I'll ask Steve about those aspects when I reach this.

The Blazor *What's New* and *Migration* content for 7.0 is almost wrapped up. With the new JS interop bits also almost finished, we almost have all of the 7.0 coverage in place. I still anticipate reaching this by the middle of next week for work.🤞🍀

**Closed** 2022-11-04 12:20 UTC
Labels: Pri1, Source - Docs.ms, Discussion, Blazor
