### ISSUE TITLE
6.0 Update needed: Web API to Azure API Management with VS

### ISSUE THREAD

**Issue by Michael-Grosser** [dotnet/AspNetCore.Docs#26130] opened 2022-06-13 09:19 UTC
In my environment I do not get startup.cs anymore. Only program.cs is available. 
How is it possible (and makes sense) to work with startup.cs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by wadepickett** [comment] 2022-06-13 17:09
@Michael-Grosser,  Thanks for pointing out the issue.   It looks like this topic has not been updated to .NET 6.0 which no longer creates a Startup.cs in the template.   That code now exists in Program.cs.  I am flagging this issue as an update needed for that topic.

**Comment by guardrex** [comment] 2022-06-13 19:50
I think this is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/25341.

**Comment by wadepickett** [comment] 2022-07-07 20:28
Closing as dupe of #25341 which is already focused on a 6.0 update of this topic.

**Closed by wadepickett** 2022-07-07 20:28 UTC
Labels: P1, Source - Docs.ms, doc-out-of-date, 6.0
