### ISSUE TITLE
The application configuration file should be supplemented with more content

### ISSUE THREAD

**Issue by v-radelg** [dotnet/AspNetCore.Docs#18276] opened 2020-05-12 20:32 UTC
@199621616 commented 6 hours ago — with docs.microsoft.com

Key, how to define? "Key": {
"Type": "Store",
"StoreName": "My",
"StoreLocation": "CurrentUser",
"Name": "CN = xxx.com"
}
},
How to use fingerprint when deploying to Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-05-16 11:50
Hello @v-radelg ... Turns out that this is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/17483, and I'll get it fixed shortly on that issue.

**Closed by guardrex** 2020-05-16 11:50 UTC
Labels: Blazor, Source - Docs.ms
