### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by Ramttid** [dotnet/AspNetCore.Docs#27198] opened 2022-10-05 14:13 UTC
Startup.cs has changed to Program.cs, things are different and I cant figure it out while using tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-10-05 18:25
Hello @Ramttid ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/13920.

**Closed by guardrex** 2022-10-05 18:25 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
