### ISSUE TITLE
SignalR not working on Blazor on .NET 5 Preview 8

### ISSUE THREAD

**Issue by nerocui** [dotnet/AspNetCore.Docs#19851] opened 2020-09-14 17:09 UTC
When I run
```csharp
hubConnection = new HubConnectionBuilder()
            .WithUrl(NavigationManager.ToAbsoluteUri("/chathub"))
            .Build();
```
on ASP.NET Core hosted Blazor wasm on .NET 5 Preview 8, exception would be thrown.

```
Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: System.Security.Cryptography is not supported on this platform.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-09-14 17:11
Hello @nerocui ... open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by BrennanConroy** [comment] 2020-09-14 17:11
Dupe of https://github.com/dotnet/aspnetcore/issues/25259 and fixed in RC1

**Closed by guardrex** 2020-09-14 17:11 UTC
Labels: :watch: Not Triaged, SignalR, Source - Docs.ms
