### ISSUE TITLE
Indicate to check the console for 404 SignalR negotiate error

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#27833] opened 2022-12-05 13:53 UTC
When I run the Hosted WebAssembly version with SignalR Chat it works in debug mode.  But when I run without debugging it does not work.  The Send button is disconnected.
And I get an error in the console:
"Failed to load resource: the server responded with a status of 405 ()"
Then it says method 405 is not allowed.

If I point the browser to the chathub URL:
localhost:portnum/chathub, 
the browser says, "Sorry, there's nothing at this address."
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio&pivots=webassembly)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-12-05 14:54
Hello @smiller7812 ... I just reached a good break point in Blazor security work this morning. I'll see if I can repro that behavior here and get back to you in a few minutes. *Stand-by* .........

**Comment by smiller7812** [comment] 2022-12-05 14:58
Thanks Luke!
________________________________

**Comment by guardrex** [comment] 2022-12-05 15:16
*Stand-by ....* I think I see what the problem is. Let me check something here. brb

**Comment by guardrex** [comment] 2022-12-05 15:20
In the console window that pops up, does it say ...

```console
Content root path: C:\Users\guard\Documents\GitHub\blazor-samples\6.0\BlazorWebAssemblySignalRApp\Client\
```

... or does it say ...

```console
Content root path: C:\Users\guard\Documents\GitHub\blazor-samples\6.0\BlazorWebAssemblySignalRApp\Server\
```

This error happens when ...

* Sticky sessions aren't in use on deployment ... obviously, not the problem here.
* The wrong app is the startup project for the solution. It has to be the **Server** project.

If it's failing and you look at the console and see that it is running the **Client** app, try selecting the **Server** project in **Solution Explorer** (i.e., highlight it by clicking once on it), and then hit the **Start without Debugging** button in the UI. When the console window appears, it should indicate that the **Server** project is running ... and hopefully no 💥 for the solution.

I'll hold this issue open for a sec while you see if you can get that to work out. In the meantime, I'm going to check the article to confirm that it says it must be run from the **Server** project.

**Comment by guardrex** [comment] 2022-12-05 15:27
Ok ... yeah ... I can't repro any problem here with starting without debugging ***as long as*** it's showing the **Server** project is the one that started.

I'll wait a little longer for you to respond, but I think we'll end up closing this as a quirk of the app startup given that the topic already calls this aspect out.

**Comment by smiller7812** [comment] 2022-12-05 15:32
Hi Luke,

One sec.
I'm going to check it out.
________________________________

**Comment by guardrex** [comment] 2022-12-05 15:35
Actually tho ... on 2nd 🤔 ... it would be nice to indicate that the reader can check the console to confirm the startup of the **Server** project. Yes, I think I will do a touch on this. However, it's going to need to wait until 23Q1. I'm buried in Blazor security right through the EOY. I'll go ahead and schedule this work. Leave this issue open. It will close automatically later when the PR merges. I'll ping you on the PR in 23Q1 when I reach this.

**Comment by smiller7812** [comment] 2022-12-05 15:41
Thanks Luke,

I just ran it again and it's fine now.
I think it might be like when you run an Angular/ASP.Net Core proj.  I get this when the Angular Console finishes compiling before the ASP.Net Core console finishes setting up the host server for the Web API.
Then I just refresh the window and it's ok.  I think it might be something like that going on.
But it is not as apparent in a hosted Blazor project.   I don't even think I thought to just refresh the browser and see if it would fix.  But I can't even reproduce at this point.

So I'm moving on to more tutorials and a MicroServices book:)

________________________________

**Comment by guardrex** [comment] 2022-12-05 15:42
Ok, that's cool.

I'm going to call out looking at the console if the negotiation fails. It's a quick one-liner probably. Still tho, I'm going to set the priority on this for 23Q1 due to all of the security work right now.

**Closed** 2023-01-11 11:44 UTC
Labels: Pri3, Source - Docs.ms, SignalR, Blazor, doc-enhancement
