### ISSUE TITLE
Is Parent-to-child binding rendundant?

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/AspNetCore.Docs#18484] opened 2020-05-26 12:27 UTC
I cant see what problem the Parent-to-child binding solves in the example about the `bind-Year` thing.

It looks to me that we could achieve the exact same thing without binding.

So in the `ParentComponent`, instead of `<ChildComponent @bind-Year="ParentYear" />`, we could just have `<ChildComponent Year="ParentYear" />`.

And then in the `ChildComponent` we could delete the `public EventCallback<int> YearChanged { get; set; }`.

It worked exactly the same way when i tested it. Because if i change the `Year` in the parent, then it would write the new value to the child.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/da-dk/aspnet/core/blazor/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-06-02 16:26
Hello @Assassinbeast ... Sorry for the delay. I'm 🏃 like crazy right now on issues.

Yes ... for a one-way case, that's correct. In fact, I'm working on how binding is described today on an issue pertaining to component parameters on https://github.com/dotnet/AspNetCore.Docs/issues/18440.

The main idea is that if you want to just one-way pass a variable value automatically down to a child, then you just need a parameter in the child to receive the value from the parent and you can set the value from the parent without `@bind`. We show it at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-parameters

As you suggest when the parent is the only thing changing the value, the parent already knows what the value is **_AND_** the child isn't expected to ever be able to change the value in the parent. Therefore, there's no need to do anything further.

I'm *tentatively* calling that scenario "one-way binding." "Tentatively" because I'm talking to engineering internally about how we describe it. I might be calling it something else by the end of the day! :smile: lol

When you want **binding** child-to-parent, then you need to use `@bind` syntax. You need the `EventCallback` in that case.

I'm going to close as a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/18440. I hope to have clarifications in the topics shortly ... within a few days if all goes well with the upcoming PR.

Thanks for commenting!

**Closed by guardrex** 2020-06-02 16:26 UTC
Labels: Blazor, Source - Docs.ms
