### ISSUE TITLE
Make content about using EF Core with Blazor Server more discoverable

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#17713] opened 2020-04-09 23:04 UTC
Lots of folks stumble when they try to use EF Core with Blazor Server because of the issues described in this doc. Unfortunately, the content in the [Use of EF DbContext fromDI](https://docs.microsoft.com/aspnet/core/blazor/dependency-injection#use-of-entity-framework-dbcontext-from-di) section isn't particularly discoverable. I think we should consider having a top level node in the Blazor docs about using Blazor with EF Core that covers this topic and any other related information.

@JeremyLikness

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-04-10 00:24
Duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/16558. I'll add the remark to that issue.

**Closed by guardrex** 2020-04-10 00:24 UTC
Labels: Blazor, Source - Docs.ms, doc-enhancement
