### ISSUE TITLE
Expand on Request/Response manipulation in Docs

### ISSUE THREAD

**Issue by brgrz** [dotnet/AspNetCore.Docs#20935] opened 2020-12-13 13:20 UTC
The docs in question (referenced below) provide too little detail into request/response operations, I should say manipulation with regards to what was previously available in asp.net with Filters/Actions.

I think it's pretty safe to assume most people come to the page referenced below trying to find detailed info on request/response manipulation, in particular modifying the response, be it either modifying the views or API responses (none of which the Docs cover).

Also, the three code samples that are included cover the I/O operations with Streams and then expand on to cover Pipelines. Why is this even here? Streams and pipelines are well documented in the IO section of the docs and have little relevance to the middleware and request/response manipulation/rewriting. So, the example topic has been chosen poorly.

Unfortunately, there's this trend of declining quality of the docs all over the ASP.NET Docs, I could post more examples of this as I have them open at the moment. I still remember the good old days of MSDN docs that were just pure joy and brilliant, sadly that's not the case anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b15fd3-39b5-3ad9-8c4e-b8160360dee9
* Version Independent ID: c33981af-93ce-d4be-a265-5d4696666c7a
* Content: [Request and Response operations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/request-response.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/request-response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by Rick-Anderson** [comment] 2020-12-15 22:11
Duplicate of #20936

**Closed by Rick-Anderson** 2020-12-15 22:11 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
