### ISSUE TITLE
Might not want to suggest WebOptimizer anymore

### ISSUE THREAD

**Issue by Eaglef90** [dotnet/AspNetCore.Docs#28233] opened 2023-01-29 00:34 UTC
The page suggests using WebOptimizer along with a few other progreams. It looks like WebOptimizer has not been touched for a while and last update was to try to get it to work on .net core 3. The current build status is failed so I am not sure suggesting this package to users is a good idea anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-7.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2023-01-29 02:02
Hello @Eaglef90 ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/20808.

**Closed by guardrex** 2023-01-29 02:02 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
