### ISSUE TITLE
Blazor Web App (.NET 8.0): Multiple Hosted ASP.NET Core Blazor WebAssembly Apps Not Documented

### ISSUE THREAD

**Issue by Schaeri** [dotnet/AspNetCore.Docs#33670] opened 2024-09-20 12:02 UTC
### Description

We have migrated our application to .NET 8.0 and are hosting multiple WebAssembly apps within a .NET ASP.NET application. We would now like to switch our clients to the new render modes (InteractiveServer and InteractiveWebAssembly). Additionally, we aim to replace all Razor Pages with Blazor components (InteractiveServer). Unfortunately, there is no documentation available on how to host multiple Blazor Web Apps in a single process. There is also no information regarding this in the migration to .NET 8.0.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md

### Document ID

96763362-f8ba-0f11-0070-da8f9f533e21

### Article author

@guardrex

**Comment by guardrex** [comment] 2024-09-20 21:06
Hello @Schaeri ... 

> there is no documentation available on how to host multiple Blazor Web Apps in a single process

The product unit has pushed multiple BWAs to .NET 10 (November, 2025). You can track their issue on that here ...

https://github.com/dotnet/aspnetcore/issues/52216

Since we don't have anything actionable for docs on it, I'll close this. There will be an issue next year for docs on the feature after they've confirmed that they did indeed get the support for it in place. As it stands, them marking it for .NET 10 just means that it's *under consideration* for .NET 10. Until they do the work to implement it, we don't track it with a docs issue.

**Comment by guardrex** [comment] 2024-09-20 21:09
I think I'll add a section in the 8.0 migration article mentioning this and providing a cross-link to that PU issue.

Leave this issue open. It will close automatically when my PR is merged. I'll get this done on Monday.

**Comment by Schaeri** [comment] 2024-09-23 06:11
Thank you for your assistance and feedback. I believe that if we now intend to use the new render modes, it would mean that we, as developers, would need to break down the projects again—one project per client. I don't think we will pursue this approach, but we will evaluate how we can utilize this information moving forward.

**Closed** 2024-09-23 13:41 UTC
Labels: Pri1, Blazor, doc-enhancement, support-request, aspnet-core/svc, blazor/subsvc
