### ISSUE TITLE
Keyword Partial does not exist. Use PartialView

### ISSUE THREAD

**Issue by RickIsWright** [dotnet/AspNetCore.Docs#25970] opened 2022-05-26 03:08 UTC
The article on partial views indicates to use the word Partial, which is not available in .NET Core 6 as far as I can find.  I was able to use PartialView in lieu of.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-05-26 10:11
Duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/25972. One issue only please, @RickIsWright.

**Closed by guardrex** 2022-05-26 10:11 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
