### ISSUE TITLE
Serious problems with syntax highlighting in *most* Blazor code samples

### ISSUE THREAD

**Issue by danysdragons** [dotnet/AspNetCore.Docs#18599] opened 2020-06-01 01:48 UTC
# Issue description

I looked through all of the pages in the Blazor docs, and found the appearance of the C# code samples within `@code` blocks to be problematic. In only a small number of cases is syntax highlighting appropriately applied, and for the _vast majority_, syntax highlighting is absent entirely. There are issues with syntax highlighting outside `@code` blocks as well, but this is not as pervasive as the issues within `@code` _blocks._

Here's just one example: https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#child-to-parent-binding-with-chained-bind

Now that Blazor Web Assembly has been officially released, developers will expect a high level of polish in the corresponding documentation.

As developers, we spend much of our day looking at code in our IDEs that is fully syntax highlighted. So when reading documentation, code where syntax highlighting is faulty or absent entirely sticks out like a sore thumb, and gives the documentation an unpolished, unfinished look.

An example of a `@code` block:

![Funky code](https://user-images.githubusercontent.com/40280395/83392254-ca39f400-a3c2-11ea-8802-2a80237e1301.png)

It's not only `@code` blocks with this issue, here's some markup with weird looking syntax-coloring:

![Funky markup](https://user-images.githubusercontent.com/40280395/83392312-e047b480-a3c2-11ea-97f2-33a2e883d2ea.png)

And again, this isn't a few isolated cases, it's like this _nearly everywhere_.

I should probably have submitted an issue earlier since I've noticed this for a while, but I assumed it would get polished up before the official release.

**Comment by Kryptos-FR** [comment] 2020-06-01 07:25
It is not just the `@code` part, the whole highlighting theme is broken for that kind of code. The HTML part has sometimes three different colors for a tag.

**Comment by danysdragons** [comment] 2020-06-01 08:41
I agree, I just emphasized `@code` since it stood out to me more. As for markup:

![Funky markup](https://user-images.githubusercontent.com/40280395/83391686-d6718180-a3c1-11ea-8b9b-6a21c3ffc1d0.png)

I think that's a good illustration of what you you described.

And again, this isn't a few isolated cases, it's like this _nearly everywhere_.

I've noticed this for a while, but assumed it would get polished up before the official release.

**Comment by guardrex** [comment] 2020-06-01 10:59
@scottaddie are u aware of any current internal work on Razor/Blazor syntax highlighting?

**Comment by scottaddie** [comment] 2020-06-01 21:03
@guardrex Closing as a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/17296. I'll follow up with engineering offline regarding updates on the situation. The docs currently use a fork of highlight.js, and the Razor language definition is incomplete. The result is the poor syntax highlighting that you're seeing.

**Closed by scottaddie** 2020-06-01 21:03 UTC
Labels: Blazor, doc-bug
