### ISSUE TITLE
I can't find view/helloworld

### ISSUE THREAD

**Issue by Sarem12** [dotnet/AspNetCore.Docs#31377] opened 2024-01-08 05:09 UTC
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-view.md

### Document ID

00c2c01d-d235-2d2d-5c96-1f33a9314382

### Article author

@wadepickett

**Comment by wadepickett** [comment] 2024-01-08 06:11
Hi @Sarem12, thanks for taking the time to let us know your experience with the tutorial.  

In the _Add a view_ section the instructions first have you create a new folder named "HelloWorld" in the existing _Views_ folder.  Then in that new directory Views/HelloWorld, you add a new item using the Razor View - Empty template and name that item "Index.cshtml"    

The result is the new item at this path:  Views/HelloWorld/Index.cshtml.

Could you provide some more information about what step you were unable to complete?

The link to the document you created this issue on  indicates you were looking at the Visual Studio version of this topic.  Is that what you were intending?  Maybe you are using Visual Studio Code?  There is a tab to click on for that version in the topic.

**Comment by wadepickett** [comment] 2024-01-09 00:59
I'm closing this issue since it is not clear what the issue is.  We could use more info here.  I will close this issue for now, but if you have more information to provide that could help us identify something that needs to change in in the doc please feel free to re-open.  Thanks.

**Closed by wadepickett** 2024-01-09 00:59 UTC
Labels: Source - Docs.ms, needs-more-info, aspnet-core/prod, aspnetcore-tutorials/tech
