### ISSUE TITLE
Azure Function dotnet isolated  using Signalr   in .NET 8 

### ISSUE THREAD

**Issue by troubleshootdoc** [dotnet/AspNetCore.Docs#31877] opened 2024-02-21 16:48 UTC
### Description

I'm looking for documentation on how to use SignalR bindings for Azure Functions using dotnet isolated mode.  (It works great in .NET 7) However, .net 8 something about the bindings has changed.  (Something that feels so simple leads you to an error running saying grpc is having an issue to I can't find anything with SignalR bindings in .net 8 for Azure Functions dotnet isolated mode) . Can someone point me in the right directions for samples or reading?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/introduction.md

### Document ID

1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1

### Article author

@bradygaster

**Comment by wadepickett** [comment] 2024-02-21 19:23
@troubleshootdoc, thanks for letting us know what you are running into.  Is the scenario you are shooting for using Azure SignalR Service bindings or are you trying to go straight from an ASP.NET SignalR app to Azure Functions?

For using SignalR Service binding we may need to address an update in this doc area for SingalR Service:  https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-csharp?tabs=isolated-process

**Comment by troubleshootdoc** [comment] 2024-02-21 23:43
it is the binding. Previously I was using this [SignalROutput(HubName = "loadtenders", ConnectionStringSetting = "AzureSignalRConnectionString")]  , where loadtenders is the HubName.  This particular function needs to send a message using the SignalR connection.   It keeps complaining that my functions.metadata is not correct.

**Comment by troubleshootdoc** [comment] 2024-02-21 23:49
![Screenshot 2024-02-21 184743](https://github.com/dotnet/AspNetCore.Docs/assets/150347565/920b9e1e-7475-4a27-b536-d28f59f173e7)
[functions.json](https://github.com/dotnet/AspNetCore.Docs/files/14366289/functions.json)

**Comment by wadepickett** [comment] 2024-02-22 05:52
Thanks for the additional details.

The error message you’re seeing, `Worker failed to index functions`, typically indicates that there’s an issue with the Azure Functions runtime being unable to properly index your function. The `System.ArgumentException: Key already exists in map` suggests that there might be a duplicate key in a map collection.

This could potentially be caused by having duplicate function names, duplicate route parameters, or duplicate SignalR hub names within your Azure Functions application. It’s also possible that there’s a configuration issue with your SignalR bindings.

Here are a few things you might check:
Function Names: Ensure that all your function names are unique across your application.
Route Parameters: If you’re using HTTP triggers with custom routes, make sure you don’t have duplicate parameter names in your route templates.
SignalR Hubs: If you’re using SignalR bindings, ensure that each hub name is unique.
[Configuration: Check your local.settings.json and host.json files for any potential issues with your SignalR binding configuration](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service)

If you have not already, do look at the [Troubleshooting guide for Azure SignalR Service](https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide) for more detailed information.   There is also a link there to notify the team of an issue you are running into that you think should be added to that guide.

I will go ahead and close this issue on the ASP.NET SignalR docs since this is related to Azure SignalR Service bindings for Azure Functions.

**Closed by wadepickett** 2024-02-22 05:52 UTC
Labels: Source - Docs.ms, SignalR, aspnet-core/svc, aspnetcore-signalr/subsvc
