### ISSUE TITLE
Any proper documentation for asp.net core with react.js project template?

### ISSUE THREAD

**Issue by storm999** [dotnet/AspNetCore.Docs#27592] opened 2022-11-11 11:57 UTC
I think, there is no documentation at all for the project template named 'asp.net core with react.js'.
There are some simple and amateur guides in external websites which do contain very basic information.

In the template, there is a controller method something like : 'public IEnumerable< WeatherForecast > Get()',
I have node idea, how this method is called, how an alternative to this method could be written etc.
When we change name of the method, nothing changes. Somehow it still works. 
When I add a 2nd method with HTTPGET attribute, the page is not loaded at all, even constructor is not called.
So does it mean that each controller page can have only 1 get and 1 post methods or what ?
Quite confusing and unclear documentation.

Probably that is why everyone is using separated web API and react projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use React with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2022-11-11 12:24
Hello @storm999 ... This is a duplicate of other issues. It's tracked by the container issue at https://github.com/dotnet/AspNetCore.Docs/issues/16209. I added this there so that your context can be considered.

**Closed by guardrex** 2022-11-11 12:24 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
