### ISSUE TITLE
Static file, multiple locations

### ISSUE THREAD

**Issue by ventureaaron** [dotnet/AspNetCore.Docs#32891] opened 2024-06-19 04:49 UTC
[EDIT by guardrex to update the metadata]

### Description

In the final blazor example for serving from multiple locations, the compiled css file seems to get lost (appname.styles.css). Debugging the webrootfileprovider seems to indicate the culprit is the Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider dropping out when we replace the webrootprovider with the compositeProvider in the example.

I worked around this with this below, but it's almost certain to not be the proper way:

```csharp
var secondaryProvider = new PhysicalFileProvider(
    builder.Configuration.GetValue<String>("serverDir:HomePath")!);
var oldProvider = app.Environment.WebRootFileProvider;
var compositeProvider = new CompositeFileProvider(oldProvider, secondaryProvider);
app.Environment.WebRootFileProvider = compositeProvider;
```

Cheers on fantastic documentation! Really appreciating all the efforts.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/static-files.md

### Document ID

25458428-030f-6acb-457e-1b4dfa722043

### Article author

@guardrex

**Comment by guardrex** [comment] 2024-06-19 08:33
Hello @ventureaaron ...

Please open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... with a few updates ...

* Tell them that you're referring to this section for use with a Blazor Web App :point_right: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#serve-files-from-multiple-locations
* When you post your code use triple-backticks above and below your code block for formatting in a GH comment with the C# code language ("\`\`\`csharp" on a line before your code ... then your code ... then on another line after with "\`\`\`"). See: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
* Please add the following to your OP so that I can follow the discussion. If we make a documentation change, it will be to add content on this to the Blazor *Static Files* article ...

  ```
  cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32891
  ```

@Rick-Anderson ... I'll relabel this issue for the Blazor article and assign to myself for work.

**Comment by ventureaaron** [comment] 2024-06-19 13:54
Thanks for your patience and instruction.

 

I’ve submitted that issue over there:
https://github.com/dotnet/aspnetcore/issues/56321

 

Hope it helps!

-aaron

**Comment by guardrex** [comment] 2024-06-19 17:19
Sorry that it didn't work out the way that I expected. Our normal workflow would've been to get an answer on the product unit's repo that I could then work into the *Static Files* article here if it turns out to be a special case for Blazor apps. Your issue was transferred to the .NET docs. I sent an email to Artak to ask him what the plan is for this issue. I'll comment back here after he lets me know how this one is going to be handled.

**Comment by ventureaaron** [comment] 2024-06-19 18:32
I probably did something wrong. Let me know if I need to resubmit anything or how else I can help.

**Comment by guardrex** [comment] 2024-06-19 18:33
Let's wait for Artak to respond to my email. I'll report back when I hear from him.

**Comment by guardrex** [comment] 2024-07-19 13:30
Confirmed that this is only a problem for BWAs (Blazor Server works with the approach in the main doc set article).

Your approach ...

```csharp
var secondaryProvider = new PhysicalFileProvider(
    Path.Combine(builder.Environment.ContentRootPath, "MyStaticFiles"));
app.Environment.WebRootFileProvider = new CompositeFileProvider(
    app.Environment.WebRootFileProvider, secondaryProvider);
```

... ✨ ***Just Works!***&trade; ✨ ... and seems fine with me as a suggested alternative.

I'm going to close the transferred issue and work from this issue.

I'll take the following actions ...

* Add a section to the Blazor *Static Files* article for this for 8.0 or later targeting BWA development.
* Place a remark in the main doc set's *Static Files* article section with a cross-link to the new guidance.

**Closed** 2024-07-19 14:41 UTC
Labels: Pri1, Source - Docs.ms, Blazor, doc-enhancement, aspnet-core/svc, blazor/subsvc
