### ISSUE TITLE
Unclear `Audience` configuration option for Blazor WASM Hosted with AAD

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#29032] opened 2023-04-20 00:03 UTC
The `Audience` configuration option mentioned in [Modify the Server appsettings.json configuration](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-7.0#modify-the--appsettingsjson-configuration) is not explained properly and actually breaks the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by hakenr** [comment] 2023-04-20 00:04
(Will be happy to submit a PR if you approve to remove it from doc.)

**Comment by guardrex** [comment] 2023-04-20 00:06
Hello @hakenr ... I'll take a look at this first thing in the morning.

**Comment by guardrex** [comment] 2023-04-20 00:11
Supply more information because it doesn't break the app ***here***. The configuration described was supplied by the product unit and extensively checked by me. Of course, a sneaky 😈 can certainly get into these docs and wreak havoc! 😆 What do you think isn't correct or explained properly about the configuration? What error are you seeing?

**Comment by guardrex** [comment] 2023-04-20 00:32
Although it's late here ... I'm just about to hit the 🛌💤 ... I just had to know what happens here if that config is removed. The user can still sign into the app, but they can't submit a valid API request thereafter ... it goes 401 💥 on the `FetchData` component with an invalid audience.

Check that you followed all of the steps and confirm that the rest of the client and server config is correct. This guidance has been like this for some five years now, and I think it's accurate.

If you figure out what the problem is with your app, please post back here what was wrong. It might be something that the topic can remark on to head off other devs hitting the same problem.

I'm going to close this now because there's not enough information to make this actionable, but feel free to post back here with more information. I certainly will re-open the issue if we need to discuss this further.

**Comment by hakenr** [comment] 2023-04-21 06:44
Hello @guardrex,
although I do not consider myself an OAuth/OIDC expert, I tried to further investigate the scenario.

# [Hosted with ADD](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-7.0)

## My observations:
1. My App ID URI has a form of `api://41451fa7-82d9-4673-8fa5-69eff5a761fd` (you refer to this variant as **trusted** in the [documentation page we are discussing](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory)).
2. The `aud` claim for access tokens (JWT) issued in this scenario has `api://41451fa7-82d9-4673-8fa5-69eff5a761fd` value.
3. The `Audience` configuration element in **Server** app, which works for me in this situation, is
```
"Audience": "api://41451fa7-82d9-4673-8fa5-69eff5a761fd"
```
(Omitting the `Audience` configuration element completely also works, but the audience is not validated in such case, I think.)

## Current documentation state
1. The [Modify the Server `appsettings.json` configuration](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-7.0#modify-the--appsettingsjson-configuration) paragraph currently instructs you to set the `Audience` element to the ` "https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}"`, which is probably valid only for App ID URI you refer to as **untrusted**.
2. The same instructions are in later in [`appsettings.json` configuration](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-7.0#appsettingsjson-configuration) paragraph.

## Expected documentation state
1. Both paragraphs should take into account the different forms of App ID URI and instruct the users to use the appropriate form for all **trusted**, **untrusted** (and custom?) variant.

---

# [Hosted with ADD B2C](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0)
I found similar confusion also in the [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0) page.

## Current documentation state
The [`appsettings.json` configuration](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0#appsettingsjson-configuration) paragraph says
> Add the following audience entry to the `AzureAdB2C` configuration:
> ```
> {
>  "AzureAdB2C": {
>    "Instance": "https://{TENANT}.b2clogin.com/",
>    "ClientId": "{SERVER API APP CLIENT ID}",
>    "Domain": "{TENANT DOMAIN}",
>    "Scopes": "{DEFAULT SCOPE}",
>    "SignUpSignInPolicyId": "{SIGN UP OR SIGN IN POLICY}"
>  }
>}
>```
But the configuration sample does not include `Audience` et al, and the "Add the following audience entry to the `AzureAdB2C` configuration" sentence probably originates from the _Hosted with AAD_ article and does not make full sense for _Hosted with AAD B2C_ article.

## Expected documentation state
The _Add the following audience entry to the `AzureAdB2C` configuration:_ sentence should be replaced with something appropriate not referring to _audience_ or removed completely.

---

I can submit a pull-request for the suggested changes, but as you mentioned, the part of the documentation in question should be reviewed by the appropriate product unit.

**Comment by guardrex** [comment] 2023-04-21 11:00
Thanks for the additional information. The trusted and untrusted publisher domains were tested, albeit several years ago, and the guidance I thought from that time worked in both scenarios.

Yes, I think Javier from the product unit should look, but I suspect that he won't have additional light to shed on trusted versus untrusted publisher domains because the original content that he sent over to publish these articles had no information on trusted and untrusted publisher domains. I added all of that content based on testing and discussion with another product unit engineer later, Jean-Marc, and the updates were focused on setting the scopes, not the audience. IIRC, all of the Azure docs on trusted/untrusted publisher domains don't (or didn't) say anything about the audience changing. I'll need to double-check that content tho.

No, don't send a PR at this point. We'll need to investigate this further before changes are made. I'll also probably want to take this on myself due to the complex nature of these articles and because the changes span several articles, perhaps also reaching into the standalone WASM group.

For now, let me ping @jmprieur ... Jean-Marc, you may recall that we discussed the subject of trusted/untrusted publisher domains several years ago for the Blazor security articles. At the time, I worked out that the ***scopes*** changed based on the behavior of Azure and my test apps, but I didn't understand why Azure insisted on a different scope format for trusted publisher domains. You clued me into the trusted/untrusted publisher domain situation. From there, I worked with the Azure docs, tested with a trusted publisher domain, and thought that I fixed up the documents sufficiently to deal with the two scenarios. I focused on the setting the scopes and cross-linking to the Azure docs on the subject. IIRC, both my trusted and untrusted domain test apps worked using the guidance here. @hakenr is saying that in addition to the scopes, ***the audience also changes***. I didn't think that was the case from testing several years ago. Can you shed any light on the audience also changing between trusted and untrusted publisher domains?

cc: @javiercn

**Comment by guardrex** [comment] 2023-04-21 11:19
> The Add the following audience entry to the AzureAdB2C configuration: sentence should be replaced with something appropriate not referring to audience or removed completely.

*Agreed!* I think you're correct. That might be due to a blown copy-paste 😈. I'll take care of that bit right now.

**Comment by guardrex** [comment] 2023-04-21 11:35
I have time to work on this right now, so let me see if I run through it with a trusted publisher domain if I can repro this.

I see my test registrations in Azure are still there, but I don't see them for the **Server** app of a hosted scenario. I see the registrations for standalone apps with a trusted publisher. I'll create new registrations and walk the entire process.

**Comment by guardrex** [comment] 2023-04-21 13:46
@hakenr ... What authority did you use in the **Client** app (`wwwroot/appsettings.json`)? Did you use `https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}` format, or did you use the `api://41451fa7-82d9-4673-8fa5-69eff5a761fd` format?

**Comment by hakenr** [comment] 2023-04-21 16:28
Oops, sorry, now I see I'm not sure what you were asking:

> @hakenr ... What authority did you use in the **Client** app (`wwwroot/appsettings.json`)? Did you use `https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}` format, or did you use the `api://41451fa7-82d9-4673-8fa5-69eff5a761fd` format?

The `Authority` element in my **Client** app is `https://login.microsoftonline.com/8a985c51-849c-4529-b45f-47c54c81b751`:
```json
{
	"AzureAd": {
		"Authority": "https://login.microsoftonline.com/8a985c51-849c-4529-b45f-47c54c81b751",
		"ClientId": "85ea08a8-5acd-4fb2-858b-397003778ea5",
		"ValidateAuthority": true
	},
	"Auth": {
		"WebServerScope": "api://d698d677-01b0-489a-b617-0fe57a4397a0/API.Access"
	}
}
```

**Comment by guardrex** [comment] 2023-04-21 16:36
Note that I'm going OOF outside of some unrelated communication with management on some other PRs. I'll get back to this issue on Monday.

I'm waiting to hear back from them on the general direction to take here because they might tell me to punt all of this publisher domain/custom domain business to the Azure docs ... i.e., it's an Azure thing, and the Azure docs should cover it. Or ... indeed ... they might tell me to work on this and try to flesh out this audience problem.

WRT your latest comment ...

> `"Authority": "https://login.microsoftonline.com/8a985c51-849c-4529-b45f-47c54c81b751",`

I see. That's interesting. Well ... I'll need to get back to this on Monday I think. If they tell me to work on this further for our docs, then I'm going to need to proceed with full testing of a custom+verified domain that's then a trusted publisher for the app registration. I'll need to see what's what in testing before trying to cover anything on this.

Javier was pinged on that email message, too. He didn't address these thornier aspects in his original content for this group of articles. I'm not sure if he'll have a suggestion to management on if I should punt or cover it. We'll just need to see how it plays out. I'll place a message here as soon as I hear back. Given that today is Friday 🎉, it wouldn't surprise me if I hear back sometime early next week.

**Comment by hakenr** [comment] 2023-04-21 18:01
The public repo which demonstrates my setup: https://github.com/havit/NewProjectTemplate-Blazor

The `Audience` configuration element we are discussing:
https://github.com/havit/NewProjectTemplate-Blazor/blob/a73ac0d323dbd335e5db5700c9d195333988c055/Web.Server/appsettings.WebServer.Development.json#L31-L34

The parent configuration file with rest of `AzureAD` elements configured:
https://github.com/havit/NewProjectTemplate-Blazor/blob/a73ac0d323dbd335e5db5700c9d195333988c055/Web.Server/appsettings.WebServer.json#L40-L47

Feel free to ask for any further details (e.g. AAD configuration).

(Of course, it's possible that I'm using it all wrong, and I'll be happy with even that finding if it puts me on the right track.)

**Comment by jmprieur** [comment] 2023-04-23 23:02
The audience of a web API needs to match the `aud` claim in the access token that will be used to call the web API (and that the web API will validate). This claim is the GUID of the web API when the AAD v2.0 endpoint is used, and the App ID URI when the AAD v1.0 endpoint is used.

So I suppose that having the GUID all the time would work?

**Comment by guardrex** [comment] 2023-04-24 00:01
Thanks @jmprieur ...

The App ID URI is for AAD v1.0 endpoints, except that when I'm not in my default directory it defaults to (and demands that I use) `https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}`. When I'm in the default directory, it defaults to the format (`api://{APP CLIENT ID GUID}`&dagger; and can be changed to any valid URI (the Azure portal lists the valid schemes).

&dagger;"APP CLIENT ID GUID" in this case is the server API **Application (client) ID** just to be clear, not the "client" as in the client ID for the client app making the request.

That's the main problem for the audience/App ID URI coverage: At least a few years ago, Azure AD and Azure docs aren't clear on why these two different App ID URIs are being used. There's been a lot of churn in the Azure docs since then, and I'll read the latest versions of everything. I hope I find an explanation over there.

When we discussed this a few years ago, I adopted the reason for this difference in App ID URI as due to the domain being trusted or not, but now it looks more like it has to do with whether or not the app registration is in the default directory. It doesn't look like its due to the `XXXX.onmicrosoft.com` domain being "trusted" because it has a ⚠️ next to it and says, "The application’s consent screen will show ‘Unverified’." That's not trusted AFAICT, so why do I receive a default of "api://{GUID}` as the App ID URI? It looks like it's due to the app being in the default directory ... or some other reason.

I'm inclined to try and cover the whole subject of what App ID URI to use along the lines of what you just said ... the dev must match the `aud` claim of the access token (in the scope provided in the client app) to the audience of the server API. If I can work out the text and examples in a generic way, I think I can resolve this problem with the guidance.

I'm going to dig into this on Monday morning and see what I can come up with.

Thanks again for your help, @jmprieur.

**Comment by guardrex** [comment] 2023-04-24 13:36
@jmprieur ... I've investigated further, and I've noticed a version difference, but it doesn't seem relevant to how the AAD registration is behaving. Just to recap, we're looking at why the Azure portal is defaulting two different App ID URIs ...

* `https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}` - Where only the `{SERVER API APP CLIENT ID}` is under dev control.
* `api://{SERVER API APP CLIENT ID GUID}` - Where the entire App ID URI is under dev control with some scheme limitations that the portal mentions when one edits the value.

Prior to just a few minutes go, the only obvious difference is that the former App ID URI is registered in a non-default AAD directory, and the latter is registered in the default AAD directory. Every app registration between these two directories default the App ID URI based on non-default and default directory where the app registration occurs.

A test app registered in the non-default directory, where I'm forced to use the `https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}` format, makes an OpenID config request at ...

```
https://login.microsoftonline.com/d7b22ce5-9645-4b38-9f0f-957d01b2a155/v2.0/.well-known/openid-configuration
```

... with the response including ...

```json
"token_endpoint":"https://login.microsoftonline.com/d7b22ce5-9645-4b38-9f0f-957d01b2a155/oauth2/v2.0/token"
```

***BUT*** ... when that app later makes a request to a server API endpoint (in my test case, it's just with the OOB `FetchData` component for weather forecast data from the `WeatherForecastController`), the access token includes ...

```json
"ver": "1.0"
```

... which I think means the `v1.0` endpoint. I think following our guidance at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#use-openid-connect-oidc-v20-endpoints

... that I can change that. However, the weather forecast data request (and its `ver` with `1.0` entry) is a downstream behavior of what AAD's app registration is defaulting to and forcing me to use for the App ID URI in the first place. There is still some factor at the app registration level that's controlling the App ID URI default. It could somehow be hidden from me that the app is somehow tied to v1.0 in the portal, but it's not obvious if that's the case, including by looking at app registration manifest files across the two directories.

I think I can write around the problem by not specifically mentioning/showing exact values for the App ID URI. Readers will use whichever format the portal provides. I'll word it along the lines of what you said ... **the audience must match**. I can at least take this approach with the guidance until I have a better answer on the AAD registration behaviors.

**Comment by guardrex** [comment] 2023-04-24 14:53
***NOTE TO SELF***: I'm placing some Azure docs resources that should be helpful here, possibly to include as cross-links for the coverage changes. There are about 20-30 articles in Azure docs that mention "App ID URI," and I'm going to look at all of them and see what I can dig up ⛏️ ...

* Scopes the possible values but doesn't say why the Azure portal would default to a particular one: https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#identifieruris-attribute
*

**Comment by guardrex** [comment] 2023-04-24 15:33
Ok ... I might have drawn a valid conclusion on it 😅 ...

* "Azure Active Directory" **tenant type**: Uses a default "tenant-verified" publisher domain as far as the App ID URI is concerned, ***BUT*** it's still described as an "unverified" (not trusted) publisher domain in the portal's **Branding & properties** UI.
* "Azure Active Directory B2C" **tenant type**: Uses a publisher domain that isn't "tenant-verified." It's also "unverified" (not trusted) as a publisher domain in the portal.

So, the ***format*** of App ID URI doesn't default to a format on the concept of "trust" (or verification) for the publisher domain. The ***tenant type*** in use where the app is registered is what controls the format.

The Azure portal is conflating "verification" concepts AFAICT. The "tenant verification" part for dictating the App ID URI seems like a separate Azure concept from the "publisher domain verification" part for dictating trust of the domain.

@jmprieur ... Does that sound right to you?

**Comment by hakenr** [comment] 2023-04-24 15:36
@guardrex Yes, my tenant type is "Azure Active Directory" (the so called B2B).

**Comment by guardrex** [comment] 2023-04-24 15:40
I thought so. I think that's ☝️ the right way to look at this.

Still tho ... the way to cover this isn't to get too deep into the weeds on it ***here*** ... in the Blazor docs. These are Azure concepts to be *mostly* covered by the Azure docs. 

What I'd like to do is cross-link that last resource that I mentioned earlier and try to mention this difference in the App ID URI ***briefly in passing*** here. I'd like to angle the coverage on how to set up the apps in the direction of the dev taking what the portal defaults to (or what they set in the case of an AAD-type tenant) and get that into the default access token scope and in the server API authority without confusion so that they ***match***.

I've already started the PR. Unless @jmprieur comes on say that I've gone 😵 sideways, I should have the PR up within a few hours, and I'll ping u (and him) on that to see how it plays out.

**Comment by guardrex** [comment] 2023-04-24 15:47
Notice how that author described it ...

> depends on where the app is registered

I wouldn't use "where" there ... "where" where??!! That's confusing.

> depends especially on whether the app is registered in a tenant

I thought ALL Azure AD apps had to be registered in a tenant. That's confusing.

> whether the tenant has tenant-verified domains

Doesn't say what that means ... it apparently means AAD vs. AAD B2C tenant types ... the former uses "tenant-verified domains" and the other doesn't. That's confusing.

I'm going to continue checking all 20-30 Azure doc resources to make sure I'm getting the best cross-link, but thus far the best is that (confusing) bit in ...

https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-configure-publisher-domain

**Comment by guardrex** [comment] 2023-04-24 17:19
It looks like, as you said @hakenr, that if the ***NON-tenant-verified*** domain is used (i.e., Azure Active Directory B2C tenant type; e.g., `https://{TENANT DOMAIN}/{SERVER API APP CLIENT ID}`) that the `Authority` in the server app settings is required ... the app 401's 💥 if it isn't present. If the ***tenant-verified*** domain is used (i.e., Azure Active Directory tenant; e.g., `api://{SERVER API APP CLIENT ID GUID}`) that the `Audience` in the server app is ***not required***.

I can't say, @hakenr, if there is a validation, per se, that doesn't take place without that server API app config setting because of course if the wrong value were set for the `Audience` in the server API app, it certainly wouldn't match what the client has in the `aud` claim of a request.

Apparently, I can only say at this point that it's required in the non-tenant-verified domain case. I'll see if I can incorporate guidance on the `Audience` setting on this basis.

**Comment by guardrex** [comment] 2023-04-24 17:48
More info on that ............

It ***assumes*** `api://{GUID}`. When I changed the App ID URI to a non-default URI of `urn://custom-app-id-uri` without setting the `Audience` for the server API app, it 💥 with a 401 until I added to the server API config ...

```json
"Audience": "urn://custom-app-id-uri"
```

... then it was happy 😄.

**Closed** 2023-04-25 20:59 UTC
Labels: Source - Docs.ms, Blazor, needs-more-info
