### ISSUE TITLE
[Blazor][Wasm] Topic for prerendering and auth

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#17648] opened 2020-04-07 10:42 UTC
Content

## Steps for supporting auth + prerendering on Blazor applications.
* The app will prerender paths for which  authorization is not required.
* Paths for which authorization is required will not be prerendered.

1. On your Client/Program.cs factor common service registrations into a separate method.
2. On your Server/Startup.cs register the services required for the UI and the applicaation to work.
  ```csharp
  services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();
  services.AddScoped<SignOutSessionStateManager>();

  Client.Program.ConfigureCommonServices(services);
  ```
  Replace `endpoints.MapFallbackToFile("index.html")` with `endpoints.MapFallbackToPage("/_Host")`
3. Create a `_Host.cshtml` page inside the pages directory, paste the contents from index.html into it and replace the `<app>Loading...</app>` tag with the following:
  ```razor
  <app>
      @if (!HttpContext.Request.Path.StartsWithSegments("/authentication"))
      {
          <component type="typeof(Wasm.Authentication.Client.App)" render-mode="Static" />
      }
      else
      {
          <text>Loading...</text>
      }
  </app>
  ```

**Comment by guardrex** [comment] 2020-04-07 11:33
Duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/17470 and resolved with https://github.com/dotnet/AspNetCore.Docs/pull/17420.

Live coverage :point_right: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1#support-prerendering-with-authentication

**Closed by guardrex** 2020-04-07 11:33 UTC
Labels: :watch: Not Triaged

**Comment by MeysamMoghaddam** [comment] 2020-09-19 12:25
how to handle api AuthenticationStateProvider in blazor wasm prerender .NET 5 Release Candidate 1 ?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/65253484/93667095-7863c980-fa98-11ea-9122-4e8bb5485f94.gif)

and in Blazor WebAssembly prerendering :
https://github.com/dotnet/aspnetcore/issues/26094

**Comment by MeysamMoghaddam** [comment] 2020-09-20 18:16
> how to handle api AuthenticationStateProvider in blazor wasm prerender .NET 5 Release Candidate 1 ?
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/65253484/93667095-7863c980-fa98-11ea-9122-4e8bb5485f94.gif)
> 
> and in Blazor WebAssembly prerendering :
> [dotnet/aspnetcore#26094](https://github.com/dotnet/aspnetcore/issues/26094)

Tnx
Resolved This Issue:
in "app" component not work <NotAuthorized> tag when use ApiAuthenticationStateProvider.
I used 
`var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            var user = authState.User;


            if (!user.Identity.IsAuthenticated)
            {
            }
`
in OnAfterRenderAsync Method

**Comment by ChristianWeyer** [comment] 2020-11-13 19:35
Do you have your sample and the solution somewhere available in Github? @MeysamMoghaddam ?
