### ISSUE TITLE
Unable to set property 'PreferExactMatches' in BlazorServerEFCoreSample

### ISSUE THREAD

**Issue by pinoli** [dotnet/AspNetCore.Docs#21227] opened 2021-01-15 07:33 UTC
[EDIT by guardrex to add the metadata ... @pinoli, use the **This page** feedback button and form at the bottom of the English-US topic to have the metadata automatically added to issues that are opened here]

# Issue description

A clean clone of BlazorServerEFCoreSample, run using VisualStudio 2019, will show `Internal Server Error` when trying to open the html page served by the IIS Express server, with the following details:
```
InvalidOperationException: Unable to set property 'PreferExactMatches' on object of type 'Microsoft.AspNetCore.Components.Routing.Router'. The error was: Unable to cast object of type 'System.String' to type 'System.Boolean'.
```

This happened on the first run, with everything untouched, while I expected a working sample from the AspNetCore.Docs

# Software versions

* [X] .NET Core 5.0.2
* [ ] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong></summary>

```console
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20601.7
 Commit:    b3b934bbf2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.520 [C:\Program Files\dotnet\sdk]
  2.1.617 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

<details>
<summary><strong>About VS info</strong></summary>

```console
Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2019   00435-60000-00000-AA700
Microsoft Visual Studio Tools for Applications 2019

Visual C++ 2019   00435-60000-00000-AA700
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.2.231
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DeployToGae Extension   1.0
DeployToGae Visual Studio Extension Detailed Info

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Entity Framework 6 Power Tools   0.9.2
Preview of useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a file containing a derived DbContext class, the following context menu functions are supported:
1) View Entity Data Model (Read-only) - Displays a read-only view of the Code First model in the Entity Model Designer.
2) View Entity Data Model XML - Displays the EDMX XML representing the underlying Code First model.
3) View Entity Data Model DDL SQL - Displays the DDL SQL corresponding to the SSDL in the underlying EDM Model.
4) Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

When right-clicking on an Entity Data Model (*.edmx) file, the following context menu function is supported:
Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu. 



Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   4.0.132
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

M Language   1.10
M Language

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.30502.00
Microsoft Office Developer Tools for Visual Studio

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.19356.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19356.0

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

SQL Server Integration Services   15.0.2000.150
Microsoft SQL Server Integration Services Designer
Version 15.0.2000.150

SQL Server Reporting Services   15.0.19124.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19124.0

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.73
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment] 2021-01-15 10:12
Hello @pinoli ... There's some confusion **_on our side_** with a Razor problem where the value is read as a string and not a boolean. You can fix that by making the value `@true` ... just add an `@` to it.

I'll take this up internally and see how we're going to handle it for the sample and the docs. Thanks for writing in on it.

**Comment by pinoli** [comment] 2021-01-15 20:16
@guardrex thank you very much for the detailed explanation and for the quick fix.
It works perfectly now 😊

**Comment by guardrex** [comment] 2021-01-15 20:17
I'm still waiting to hear back from the product unit. Given that we're going into a 3-day holiday weekend, it might be Tuesday before the word comes back. I'll post an update here when I know what direction we're going with it.

**Comment by guardrex** [comment] 2021-01-16 15:24
Ah ... I think this is either an SDK and/or package problem.

Get and install the 5.0.2 SDK just to make sure it isn't the problem ...

https://dotnet.microsoft.com/download/dotnet/5.0

... and then nuke package caches ...

```dotnetcli
dotnet nuget locals --clear all
```

... and then make sure that you've updated all packages to latest in the app. My test app (that didn't require me to use `@true`) now has ...

```xml
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.2" PrivateAssets="all" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.2" />
<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.2" />
<PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
```

... and that lick'ed IT ... it runs now without complaining about the string/boolean problem for `PreferExactMatches`.

If it is packages that are causing the problem, it might be because a pegged patch package (5.0.1) is holding back 5.0.2 packages from the app. Not sure about that. I just know that between the SDK update to 5.0.2 and setting my packages to 5.0.2 solved it for my test app.

I'm going to go ahead and close this but keep an :ear: open for more devs who hit this. If more devs do, then I'll see what we need to do in the *Migration* topic to help. The topic already calls out installing the latest SDK and upgrading packages, so we might be ok going forward now that the SDK is at 5.0.2 and package references should roll forward to 5.0.2 or later 🤞. I have other test apps lying around here, so if I need to do more investigation on the cause, I'll try tinkering with the SDK version (via a `global.json`) and package versions (via pegging the EF Core packages to `5.0.1`) to see if I can narrow it down to the exact problem. If no one else writes in tho, it isn't worth the trouble to investigate further.

**Comment by moh-hassan** [comment] 2021-01-22 17:11
I installed SDK v `5.0.102` and Vs2019 v `16.8.4` and get the same issue.
Then I modified `app.razor` as [here](https://github.com/dotnet/AspNetCore.Docs/pull/21097/files) by @guardrex 
```
<Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
```
And it's working fine.
Thanks @guardrex

**Comment by guardrex** [comment] 2021-01-22 17:16
@moh-hassan ... Try something for me with that app ...

1. Confirm that if you change it back to just `true` (no `@`) that it goes back to breaking 💥.
2. Nuke your package cache at a command prompt with ...

   ```dotnetcli
   dotnet nuget locals --clear all
   ```

3. Delete the `bin` and `obj` folders in the app.
4. Rebuild (which will restore the packages, too) and run the app again.

See if it goes away with the `true` (no `@`) after doing that. What we're checking here is that installing the SDK isn't enough ... cached packages are somehow breaking it. Even if after doing that ☝️ if it still breaks with just `true`, I have another thing that we can take a look at. I'll discuss that with you after you get back to me.

**Comment by moh-hassan** [comment] 2021-01-22 18:31
@guardrex 
I did the same steps 1-4  as you described above and get the same Error of OP.
Here is the stack Exception
[stack.txt](https://github.com/dotnet/AspNetCore.Docs/files/5857832/stack.txt)

**Comment by guardrex** [comment] 2021-01-22 18:35
@moh-hassan ... Ok ... next ... can you paste in here your package references from the app's project file (if there are any)? Like this inside of triple-backticks ...

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />
  <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.0" />
  <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
</ItemGroup>
```

**Comment by guardrex** [comment] 2021-01-22 18:46
Actually ... if you don't have any sensitive info in your project file, go ahead and paste the whole file into a comment here.

**Comment by moh-hassan** [comment] 2021-01-22 19:20
@guardrex 
My original project
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.2" />
  </ItemGroup>
</Project>
```
then paste the references above to the project:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.2" />
  </ItemGroup>
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />
  <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.0" />
  <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
</ItemGroup>
</Project>

```

Then run,  the browser show white page (empty page without Exception). 
Pressing F12 (dev tools in FireFox)  I find error 404 ([HTTP/2 404 Not Found]
The complete project with bin folder is attached.
[BlazorServerDbContextExample.zip](https://github.com/dotnet/AspNetCore.Docs/files/5857993/BlazorServerDbContextExample.zip)

**Comment by guardrex** [comment] 2021-01-22 19:45
When I referring to the sample and showing those package references, I wasn't really addressing this specific sample, so I didn't mean for anyone to put those exact package references into their app. What I showed was from another sample that I have that I use for various testing scenarios.

Let me check something and get back to you.

**Comment by moh-hassan** [comment] 2021-01-22 20:00
@guardrex
Something strange but good news :)
I Reference the next library v 5.0.1 
```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />
```
 and my project is:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.2" />
	</ItemGroup>
    <!-- Use v 5.0.1-->
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />
	</ItemGroup>
</Project>

``
It works fine :) :)
It seems there is a breaking change in Microsoft.AspNetCore.Components.WebAssembly v 5.0.2

**Comment by guardrex** [comment] 2021-01-22 20:10
Yes, it was fixed at 5.0.2, and 5.0.2 should come in automatically without having to provide a package reference, but that's not happening here. It's also strange to me that that a Blazor Server app requires the package reference at all.

@captainsafia ... What we've found out tinkering a bit more with `PreferExactMatches` is that for ...

* Blazor WASM ... Neither setting the version of `Microsoft.AspNetCore.Components.WebAssembly` to 5.0.0 or 5.0.1 exhibits roll-forward behavior to 5.0.2. One apparently has to set it explicitly to 5.0.2 or later.
* Blazor Server ... Requires a package reference to `Microsoft.AspNetCore.Components.WebAssembly` for 5.0.2, which normally one wouldn't mess with. I thought that based on the announcement and our discussions that this was hosting model agnostic. We don't discriminate in our current guidance for `PreferExactMatches` ... we say that *all Blazor apps should get it.*

Otherwise for both hosting models if they don't manage the package+version, the dev has to use `@true` or suffer a :boom: at runtime.

Can u advise further?

**Comment by moh-hassan** [comment] 2021-01-22 23:28
@guardrex 

Just I noticed that:
- The cli command for blazor server `dotnet new blazorserver`  generate App.razor using @true:
```
<Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
```
- Vs 2019 v16.8.4 (including sdk 5.0.102) generate app.razor without `PreferExactMatches`:
```
<Router AppAssembly="@typeof(Program).Assembly">
```

- This [document](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#recommended-action)  for migration of ASP.NET Core 3.1 to 5.0 include:
```
Add the PreferExactMatches attribute to the Router component in the App.razor file to opt into the correct behavior:

<Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="true">
When PreferExactMatches is set to true, route matching prefers exact matches over wildcards.

 Important

All apps should explicitly set PreferExactMatches to true.

The ability to set PreferExactMatches to false or leave it unset is only provided for backward compatibility.

When .NET 6 is released, the router will always prefer exact matches, and the PreferExactMatches option won't be available.
```

**Comment by guardrex** [comment] 2021-01-22 23:43
I'll defer to @captainsafia for the first two points ...

1. Was Blazor Server always supposed to use `@true`, while Blazor WASM was just supposed to use 5.0.2.
2. I can't explain the 2nd bullet at all. 😕

The third point is correct with the notes that I mentioned earlier ... no `@` under those (strange) conditions.

**Comment by sundhaug92** [comment] 2021-01-23 21:46
I suggest that for now the docs list the `@true` for server, until it's fixed

**Comment by guardrex** [comment] 2021-01-23 22:13
@sundhaug92 ... I'm going to wait and hear from @captainsafia. Prefixing the value isn't the only unknown: `PreferExactMatches` isn't apparently available in a Blazor Server app without the WASM package, which doesn't make sense. The announcement and info that I received seems to indicate that this attribute is hosting model agnostic. You're right about the roll-forward behavior. That can be fixed across the board if everyone always prefixes.

**Comment by captainsafia** [comment] 2021-01-24 21:43
@guardrex This came up during one of our standups. Let's include the `@` in the parameter for the following reasons:

- Without it, completions and syntax highlighting break in VS.
- We already use the `@` prefix in other parameters in the `App` component.
- We haven't gotten around to updating the targeting packs to resolve this issue.

All in all, I think including it will unblock people and reduce the amount of confusion here.

**Comment by guardrex** [comment] 2021-01-24 22:39
@captainsafia ... I'll update it this evening and get it live quickly.

What about Blazor Server requiring the `Microsoft.AspNetCore.Components.WebAssembly` package in order to use the attribute ... this is hosting model agnostic, right?

**Comment by captainsafia** [comment] 2021-01-24 23:25
Yes, the attribute is hosting-model agnostic. Setting it impacts both Blazor Server and Blazor WASM applications.

The error that people are running to impact Blazor Server and certain scenarios of Blazor WASM, so that's why we are seeing different behavior there.

> If it is for Blazor Server, too, am I not doing something correctly to get the attribute to light up?

There's some work we need to do on the dev team to make sure that Blazor Server compiles against the correct bits. For now, prefacing with `@` should avoid running into these issues.

**Comment by guardrex** [comment] 2021-01-24 23:33
Ah ... I see what's going on here. IntelliSense doesn't light it up (without the WASM pacakge), but that's ok as long as the value is prefixed with `@`. :+1:

I'll get this updated shortly and live in the docs tonight.

**Closed** 2021-01-24 23:47 UTC
Labels: Blazor, P0, doc-bug
