### ISSUE TITLE
Page content not current

### ISSUE THREAD

**Issue by FAA-MichaelC** [dotnet/AspNetCore.Docs#26969] opened 2022-09-12 15:15 UTC
This page is listed as being a part of .Net 6, but several references seem to be out of sync.  The page does mention that, due to changes in .Net 6, the WebApplicationFactory must be positioned to reference the Program class since Startup is no longer used, but the following paragraphs that involve the WebApplicationFactory still reference the Startup class.   I am in the process of converting an application from .Net Core 3.1 to 6 and updating the integrations tests is not going well.  I'm getting errors in every test that make no sense, and this page is not helpful at all.  I have created two custom instance of WebApplicationFactory, and now after upgrading every project to .Net 6, none of my integration tests pass.  Not only do they all fail, but they fail because of exceptions that occur in the custom WebApplicationFactory classes, so the tests are not actually being executed due to problems in the initialization of the tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2022-09-12 18:45
[Duplicate of these](https://github.com/dotnet/AspNetCore.Docs/issues?q=%22f499b131-8b14-7e10-1728-543fdd5a5656%22+is%3Aopen).

**Closed by Rick-Anderson** 2022-09-12 18:45 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
