### ISSUE TITLE
Router has no property PreferExactMatches

### ISSUE THREAD

**Issue by rlyme** [dotnet/AspNetCore.Docs#20838] opened 2020-12-02 15:28 UTC
Following the recommended action to add the PreferExactMatches attribute to the Router, results in runtime error:

InvalidOperationException: Object of type 'Microsoft.AspNetCore.Components.Routing.Router' does not have a property matching the name 'PreferExactMatches'.

Even the docs doesnt specify this Property? https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.routing.router?view=aspnetcore-5.0

I installed .net sdk 5.0.100 (x64) and changed TargetFramework net5.0 etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2020-12-02 15:40
@javiercn ... Requires a package reference to be set explicitly? I thought roll-forward behavior would pick this up.

**Comment by guardrex** [comment] 2020-12-02 15:43
@rlyme ... Can you delete your `bin` and `obj` folders and nuke your package cache with `dotnet nuget locals --clear all` ... then restore and rebuild.

**Comment by javiercn** [comment] 2020-12-02 15:44
@guardrex this patch hasn't been published yet

**Comment by javiercn** [comment] 2020-12-02 15:45
AFAIK rolling behavior should apply once it's released.

**Comment by guardrex** [comment] 2020-12-02 15:48
I see.

(*Now, he tells me!* 😄 lol)

I guess it will be soon, right? ... If soon, we can skate by without temporarily dropping the coverage from the topics. If it will be days tho, I'll need to temporarily comment out the coverage and restore later.

**Comment by javiercn** [comment] 2020-12-02 15:50
It'll be a few days I think.

Sorry, I should have mentioned it on the original issue.

**Comment by guardrex** [comment] 2020-12-02 15:52
No worries ... I'll comment out the coverage with an "addresses" PR for now.

@rlyme ... When you see this issue close with a "fixes" PR later, that means that the package is out.

**Comment by rlyme** [comment] 2020-12-02 15:54
allright, thanks for your fast reply (y)

**Comment by jhomminga** [comment] 2020-12-11 07:52
just learning, if helps someone, needed to remove PreferExactMatches="@true" from App.razor else IIS gives error on render

to reproduce:
from C:\
dotnet new blazorserver -o foo --not-https -f net5.0 
cd foo 
dotnet publish --configuration release --output C:\foo_out
will get error in IIS

verified aspnetcorev2 module iis 
installed hosting bundle
installed the urlrewrite2

**Comment by guardrex** [comment] 2020-12-11 10:13
@jhomminga ... Open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by guardrex** [comment] 2020-12-11 10:35
To fully resolve this I need to call out the param across appearances of `App.razor`. I'd prefer not to create a bunch of 5.0 to <6.0 code blocks. I'll consider two alternatives technique to deal with it before creating code blocks ...

* A short NOTE INCLUDE that cross-links to the Migration topic content for the details.
* Use an ellipsis in `<Router>` tags to signify params without showing them (e.g., `<Router ...>`), which gets us off the hook in cases where the param set is irrelevant to whatever is being discussed by the text.

I'll see what I can do immediately after the current crop of PRs is merged. Leave this issue open. It will close automatically when the PR merges.

**Closed** 2020-12-15 12:36 UTC
Labels: P0, Source - Docs.ms, doc-enhancement

**Comment by clockwiseq** [comment] 2021-01-25 22:20
Why was this marked as done?  I can reproduce this from @jhomminga's example steps.

**Comment by guardrex** [comment] 2021-01-25 22:25
@clockwiseq ... I told @jhomminga  to open for the product unit, and I don't know if that occurred. If there's a lingering issue that pertains only to IIS, open it for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

What we're going to do in docs for the time being for `PreferExactMatches` is tell all devs to use `@true` throughout 5.x. At 6.0, the attribute will go away. If the product unit needs to modify the guidance in the docs for an IIS edge case of some sort, then we'll open a new issue for that and proceed from there. If you do open an issue with them, please add a `cc: @guardrex` to your opening comment so that I can get the pings on the discussion (thanks in advance).

**Comment by guardrex** [comment] 2021-01-25 22:27
@clockwiseq ... btw ... I wouldn't be surprised if there is an edge case for anything, including IIS, based on my recent discussion with them. Safia, one of the engineers, told me that they are actively working on things to resolve issues with the attribute. Search over there using the search text "PreferExactMatches" (open and closed issues) to see if they're already working on things. If you find an open issue, you can just discuss it with them on that. If you don't find an issue, then you can open a new issue with them.

**Comment by clockwiseq** [comment] 2021-01-26 13:34
So you're saying this should be an IIS issue?  I arrived here because this was the only documented issue with this "PreferExactMatches" in it.  I simply created a new BlazorServer app in VS and attempted to have Azure DevOps publish it to my web server (IIS) and it doesn't execute/render.  I get:

InvalidOperationException: Object of type 'Microsoft.AspNetCore.Components.Routing.Router' does not have a property matching the name 'PreferExactMatches'.

Not sure that's the expected behavior out of the box, so am I supposed to remove the PreferExactMatches="@true" from the App.razor?

**Comment by javiercn** [comment] 2021-01-26 13:37
@clockwiseq I believe you need to update the runtime on the deployment machine, the SDK you are using seems to contain the change, but the runtime you are using on the deployed machine seems it doesn't, and that is causing the issue I believe.

/cc: @pranavkm

**Comment by guardrex** [comment] 2021-01-26 13:48
Sorry @clockwiseq ... I assumed that you did that :point_up:.

We don't remind devs about installing a new Hosting Bundle in the *Migration* docs; however, we could do that.

**Comment by clockwiseq** [comment] 2021-01-26 14:06
Aaaah, ok, I will try that.  I did remove the attribute and it worked, but I will add it back and update the hosting bundle on the web server.  I sure appreciate the help @javiercn and @guardrex!

**Comment by artbavial** [comment] 2021-12-10 17:54
> просто учусь, если кому-то помогает, нужно удалить PreferExactMatches="@true" из приложения.в противном случае IIS выдает ошибку при рендеринге
> 
> для воспроизведения: из C: dotnet новый blazorserver -o foo --нет-https -f net5.0 cd foo публикация в dotnet --выпуск конфигурации --вывод C:\foo_out появится ошибка в IIS
> 
> проверен модуль aspnetcorev2 iis установлен пакет хостинга установлен urlrewrite2

Спасибо! Очень помог.
