### ISSUE TITLE
Is there any demo on Blazor ServerSide?

### ISSUE THREAD

**Issue by v-radelg** [dotnet/AspNetCore.Docs#18273] opened 2020-05-12 20:10 UTC
@LuohuaRain commented on [Tue May 12 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/267)

Thanks.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [ASP.NET Core 中的身份验证和授权SignalR](https://docs.microsoft.com/zh-cn/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

---

@srvbpigh commented on [Tue May 12 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/267#issuecomment-627419837)

Hello, @LuohuaRain
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment] 2020-05-13 12:26
Duplicate of #18268.

**Closed by guardrex** 2020-05-13 12:26 UTC
Labels: Source - Docs.ms, duplicate
