### ISSUE TITLE
Unclear description of AuthorizeView component

### ISSUE THREAD

**Issue by shanemikel** [dotnet/AspNetCore.Docs#20462] opened 2020-11-10 00:17 UTC
I'm evaluating Blazor Server as an option for an internal facing application.  In my case, I will have many pages in which all content and behavior is restricted to authorized users based on various groups/roles.

```
<AuthorizeView Roles="groupsAllowedOnThisPage">
    @secureChildContent
</AuthorizeView>
```

Is this secure for interactive components which bind events within the `AuthorizeView`?  For instance, does the following solution expose `MySecureMethod` to an unauthorized user through the SignalR circuit?

```
@page "/secure-page"
@attribute [Authorize]

<AuthorizeView Roles="SecurePage">
    <button @onclick="MySecureMethod">...</button>
</AuthorizeView>

@code {
    private void MySecureMethod() { ... }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-11-10 00:34
Hello @shanemikel ... AFAIK, the C# code stays safely on the server.

@SteveSandersonMS ... Do you want correct/extend on this point: Is there any potential leakage of C# code (`@code` block) from the server to the client for Blazor Server?

**Comment by shanemikel** [comment] 2020-11-10 00:38
It's not the source code I'm worried about leaking, it's execution of the code path.  Is it possible for somebody to mess around with the dev tools and the SignalR socket to invoke `MySecureMethod` even though they aren't authorized and the button is never rendered?

**Comment by guardrex** [comment] 2020-11-10 00:46
Oh, I see what you mean. I thought by "expose" you meant could the method contents be exposed. 

> execution of the code path

AFAIK, *no*, that wouldn't be possible because the user's auth state is on the server. However, I'm a **_docs_** :cat2:, and that's my impression from the remarks that the product unit has made. We need a **_framework_** :cat2: (e.g., Steve ... perhaps @captainsafia can remark) to absolutely confirm security on this point.

**Comment by guardrex** [comment] 2020-11-10 13:12
@shanemikel ... I'll elaborate on that: The auth state is known for the user on the server, **_AND_** the method will require an auth state check in this scenario. We have existing examples of it at ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1#authenticationstateprovider-service
* https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1#procedural-logic

Let's hear from the product unit further before I make an update. I think calling it out there where the `AuthorizeView` is described makes sense.

**Comment by shanemikel** [comment] 2020-11-10 20:05
Ideally for me, Blazor Server wouldn't bind an event listener if no binding element is rendered, and I can avoid duplicating authorization logic in all my event handling methods.

If the method *is indeed* still bound to a SignalR event even if no bound element is rendered, I am curious to know how difficult it would be for the client to manually trigger it (i.e. does it require guessing a random number of event listener ID?).

**Comment by guardrex** [comment] 2020-11-10 20:09
... but the component itself is available anonymously, so I'm worried that a malicious user could trigger it ... as you say ... hacking without the button being rendered. We're drifting just a bit into a **_product unit feature request_** :smile:. You can certainly ask about it on the product unit repo. Open an issue to ask about this scenario at ...

https://github.com/dotnet/aspnetcore/issues

... it will be just about an exact duplicate of your opening issue comment.

Cross-link to this issue and please add a `cc: @guardrex` to your opening comment.

Leave this issue open: I agree that a few words on this scenario would be good to include in the `AuthorizeView` section of the topic. This docs issue will close when the docs PR merges. I won't make any updates tho until we hear back on your engineering issue.

**Comment by shanemikel** [comment] 2020-11-10 21:27
@guardrex Sorry, I forgot to mention that I have `@attribute [Authorize]` in my `_Imports.razor` file.  I'll update my example.

**Comment by guardrex** [comment] 2020-11-10 22:07
In that case, it's not accessible without authentication, so you should be fine. That includes the methods in the `@code` block. We have a warning from the product unit about child components tho ...

> Only use `[Authorize]` on `@page` components reached via the Blazor Router. Authorization is only performed as an aspect of routing and not for child components rendered within a page. To authorize the display of specific parts within a page, use `AuthorizeView` instead.

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#authorize-attribute

... which I would only be concerned about for non-routable components embedded in the page. In that case, I would use the procedural code that they recommend to check the user is authenticated in the child component's code.

**Comment by shanemikel** [comment] 2020-11-11 01:22
2 Points of clarification:
- The methods in `@code` would only be accessible to _authenticated_ users, but if Roles are only specified in the `AuthorizeView` component and not in the `Authorize` attribute, will the methods only be accessible to _authorized_ users?
- To complicate my use-case a bit further, although I'm using the `Authorize` attribute in the page itself (via `_Imports.razor`) I'm actually splitting out the `AuthorizeView` component for a common auth error message across pages (example follows).

AuthorizeWorkflow.razor (Component):
```
<AuthorizeView Roles="@Groups">
    <Authorized>
        @ChildContent
    </Authorized>
    <NotAuthorized>
        <h3 class="text-danger">Error</h3>
        <p class="text-danger">You are not authorized to access this page.</p>
    </NotAuthorized>
</AuthorizeView>

@code {
    [Parameter]
    public string Groups { get; set; }

    [Parameter]
    public RenderFragment ChildContent { get; set; }
}
```
Altered `/secure-page` example:
```
@page "/secure-page"
@attribute [Authorize]

<AuthorizeWorkflow Groups="SecurePage">
    <button @onclick="MySecureMethod">...</button>
</AuthorizeWorkflow>

@code {
    private void MySecureMethod() { ... }
}
```

**Comment by guardrex** [comment] 2020-11-11 12:49
I see your point (referring to your first bullet and our prior discussion and prior example) ... it looks like Javier took that into account in his code example ... he has you check the user's role at ...

```csharp
var authorized = ...
```

... so they're authenticated for the component. They only see :eye: button if they're authorized (their role). The method only runs after the protected handler checks that they are in the right role.

WRT the split out (second bullet) ... I think 🤔 (based on the quick look at Javier's suggestion) that you can adapt that to your approach. WRT the `[Authorize]` attribute there, it seems good ... you are taking into account the `[Authorize]` warning in the doc that states you should use an `AuthorizeView` in a non-routable component (`AuthorizeWorkflow.razor`) and not rely on the attribute to provide the authn there.

Of course, testing will confirm the behaviors. Once you have the code in place, you can stick a test button out there (outside of `AuthorizeWorkflow`) that displays for all authn users (irrespective of their role) that would trigger the method for a **_user in the wrong role_** and confirm that the method **_does NOT run_** for them. Then, of course, it should run for a user in the right role given Javier's approach.

I think I can produce some documentation to cover this scenario ... *maybe* ... we do often avoid documenting very advanced and edge case code. However, this seems like a good pattern to cover, and I like what Javier did.

This will need to wait a bit ... "a bit" :smile: ... a month ... *or three!* 🏃😅. I have a ton of work to do over the ⛄ *holidays* :gift:. I'll get to this as soon as I can.

**Comment by guardrex** [comment] 2020-11-12 20:46
Ok ... we have our answer now. Closing on the basis of the product unit feedback on the scenario.

**Comment by shanemikel** [comment] 2020-11-13 00:05
Thanks @guardrex

**Comment by guardrex** [comment] 2020-11-13 00:17
> default event handlers for non-rendered elements are unable to be invoked

**Closed** 2020-11-13 11:12 UTC
Labels: Blazor, P1, Source - Docs.ms, doc-enhancement
