### ISSUE TITLE
As a guide on how to install Blazor Webassembly Hosted App in IIS - this document is a huge disappointment. No, actually it is a disaster

### ISSUE THREAD

**Issue by qplace1** [dotnet/AspNetCore.Docs#26856] opened 2022-08-28 22:36 UTC
To say that this doc is a disservice for a developer is an understatement. I have a basic Blazor Webassembly hosted solution that I need to install on IIS. Please tell me what steps do you want me to follow? Nothing fancy, nothing specific...
Step 1.
Step 2..
etc.
Instead I am getting a sequence of unclear paragraphs without referencing Bl.WASM hosted solution. What am I suppose to do...
SAD.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-08-28 23:02
Hello @qplace1 ... A hosted WASM app is just a plain old ASP.NET Core app as far as IIS hosting guidance is concerned, unless there are special circumstances (e.g., sub-app hosting, multiple WASM hosted apps, and a few other special cases). I just cleaned up the current guidance in the overview article ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#hosted-deployment-with-aspnet-core

... on the PR that was merged on Friday ...

https://github.com/dotnet/AspNetCore.Docs/pull/26842

... but it hadn't merged to the live doc set on ...

https://github.com/dotnet/AspNetCore.Docs/pull/26849

... so I'll do that now. Give it a while to update ... anywhere from 5 minutes to 30 minutes or so from now (8/28 6pm CST).

I'll close this as fixed since your ask was what that PR was designed to resolve.

**Closed by guardrex** 2022-08-28 23:02 UTC
Labels: Source - Docs.ms, Blazor

**Comment by guardrex** [comment] 2022-08-28 23:07
That was quick 🏃‍♂️ ... there are low demands on the build system on the weekend like this. That updated coverage is at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#iis

**Comment by guardrex** [comment] 2022-08-28 23:15
Actually, I think I'll add a line for WASM to that new bullet list in the overview. I just put it up on ...

https://github.com/dotnet/AspNetCore.Docs/pull/26857

After I merge that to `main`, I'll take it live immediately, so you'll see the final structure of the content shortly.
