### ISSUE TITLE
Problem Configuring certificate authentication in ASP.NET Core using Docker

### ISSUE THREAD

**Issue by nizarelouaer** [dotnet/AspNetCore.Docs#18709] opened 2020-06-08 15:08 UTC
I have an asp.net core API which uses both http and https. To enforce the certificate use, I added the following in my program.cs:
```
 private static IWebHost BuildWebHost(IConfiguration configuration, string[] args) =>
           WebHost.CreateDefaultBuilder(args)
           
            .UseKestrel(options =>
            {

                options.ConfigureEndpointDefaults(listenOptions =>
                {
                    listenOptions.UseConnectionLogging();
                });
            })
               .CaptureStartupErrors(false)
               .UseStartup<Startup>()
            
                .ConfigureKestrel(o =>
                {
                    o.ConfigureHttpsDefaults(o =>
                o.ClientCertificateMode =
                    ClientCertificateMode.AllowCertificate);
                })

```
If I run my app in my windows machine, everything works correctly. Nevertheless, when I run it in my docker desktop or even in an ubuntu machine I am not able to call my https endpoint and I am getting a "ERR_CONNECTION_CLOSED". I am still able to call my http endpoint. In my docker compose ?I am setting correctly all the parameters:

```
environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;https://+;http://+;
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=jtHxcTN
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro 
```
I even tried to create a new certificate on my ubuntu using openssl but I am still having the same problem.
PS: If I comment the line:
```

.ConfigureKestrel(o =>
                {
                    o.ConfigureHttpsDefaults(o =>
                o.ClientCertificateMode =
                    ClientCertificateMode.AllowCertificate);
                })
```
I am able to call my https endpoint, but no certificate is sent to the server.
Any help ?
Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by guardrex** [comment] 2020-06-08 15:20
Hello @nizarelouaer ... Is this a duplicate of or related to (i.e., they can be worked together) of https://github.com/dotnet/AspNetCore.Docs/issues/18702?

**Comment by nazzour** [comment] 2020-06-08 15:34
> Hello @nizarelouaer ... Is this a duplicate of or related to (i.e., they can be worked together) of #18702?

Yes it is related to the same issue. It is really a blocking issue for those who want to work with https in a containerized environment.

**Comment by guardrex** [comment] 2020-06-08 15:52
It's best to combine them on the same issue. Move one of the comments to the other issue and close it.

**Comment by blowdart** [comment] 2020-06-09 14:23
What happens if you switch from AllowCertificate to RequireCertificate? It's require that would force a browser to ask the user for one?

**Comment by nizarelouaer** [comment] 2020-06-09 15:15
When I switch to RequireCertificate, to RequireCertificate, the browser asks for the certificate however I dont receive any certificate in my server. the Request.HttpContext.Connection.ClientCertificate is null. This happens only using Docker because when I run the app in my local Windows machine it works correctly.

**Comment by blowdart** [comment] 2020-06-09 17:12
Forgive me, because I don't know docker well, but it acts as a proxy doesn't it? If it doesn't pass on the certificate, then you probably need to look at nginx or apache as the proxy

**Comment by nizarelouaer** [comment] 2020-06-10 00:33
I guess it is not a docker issue, I made a test using Ubuntu machine without docker and I am having the same behavior. It is really a .net core issue I think

**Comment by Rick-Anderson** [comment] 2020-06-10 05:15
@nizarelouaer can you create the simplest possible project that reproduces the issue (works on Windows, fails on Ubuntu? 

Client certificates are negotiated per-connection and must be be negotiated at the start of the connection before any HTTP data is available. At the start of the connection, only the Server Name Indication (SNI) is known. The client and server certificates are negotiated prior to the first request on a connection and requests generally won't be able to renegotiate. Renegotiation is prohibited in HTTP/2.

**Comment by Rick-Anderson** [comment] 2021-05-12 23:01
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

**Closed by Rick-Anderson** 2021-05-12 23:01 UTC
Labels: Source - Docs.ms, needs-more-info
