### ISSUE TITLE
Your instructions don't work

### ISSUE THREAD

**Issue by Roscoe-Sandstone** [dotnet/AspNetCore.Docs#29108] opened 2023-04-27 15:51 UTC
Getting Started with Blazor TextBox Component[Enter feedback here] doesn't work.  I realize that teaching by the "Monkey See-Monkey Do" philosophy eases the burden on your tech writers, but it certainly leaves a bad taste in one's mouth concerning everything associated with Blazor and Syncfusion.

Going thru the "procedure" you have outlined ends up with nothing like you are espousing. Your instructions are written by and for someone who already has experience with your product.  Imagine buying a TV set that has no controls on the set itself.  Instead, what you get is a remote control unit with 15 buttons, and none of the buttons are labeled or marked.  You might sell, perhaps, a dozen units before the word gets out that the TV set is not worth the money or time, and that all you will end up with is total frustration in that you will spend most of your effort fighting the remote control rather than watching TV programs.  Watching TV programs presumably being the reason you got the TV set to begin with.

Fire your  tech writing staff, immediately.  They are not doing their job.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment] 2023-04-27 16:49
Hi @Roscoe-Sandstone, sorry to hear about the bad experience.   Did you mean to associate this issue with one of the Blazor SignalR topics?

I understand what you are referring to that merely walking through procedures are not as helpful.

**Comment by guardrex** [comment] 2023-04-27 16:49
@Roscoe-Sandstone ... 

> Blazor TextBox Component

Can you confirm that you're looking at the correct article? It looks like you opened this from the wrong topic.

Also, there's no such component in Blazor named a "TextBox component." There's an `InputText` component ... as described in the [Blazor *Forms and input components* article](https://learn.microsoft.com/aspnet/core/blazor/forms-and-input-components#built-in-input-components).

**Comment by guardrex** [comment] 2023-04-27 16:49
Sorry Wade ... we must have hit "Comment" within seconds of each other.

**Comment by wadepickett** [comment] 2023-04-27 16:51
No worries.  It does look like this was intended for one of the Blazor topics, feel free to assigning it to yourself.

**Comment by guardrex** [comment] 2023-04-27 16:51
I'll update the metadata after we know which article applies.

**Closed** 2023-04-27 19:02 UTC
Labels: Source - Docs.ms, SignalR, Blazor, needs-more-info

**Comment by guardrex** [comment] 2023-04-28 11:20
@Rick-Anderson ... You were right to close this. I think @Roscoe-Sandstone is referring to an external (non-MS) topic at ...

https://blazor.syncfusion.com/documentation/textbox/getting-started

@Roscoe-Sandstone ... We have no direct relationship or control over what they published. Contact Syncfusion support for your request.
