### ISSUE TITLE
Doesnt work, even though recent has never been tested, waste of people time, very poor

### ISSUE THREAD

**Issue by weedylan1** [dotnet/AspNetCore.Docs#29154] opened 2023-05-03 09:58 UTC
Code Doesnt work, even though recent has never been tested, waste of people time, very poor

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2023-05-03 10:14
Hello @weedylan1 ... Yes, I'm not sure if it was tested for 7.0, and I do see that the SDK prereq should be updated. However, "it doesn't work" doesn't give me very much to go on: Which .NET version are you using ... 7.0? Which hosting model ... Blazor Server? What is the error/behavior?

**Comment by guardrex** [comment] 2023-05-03 10:23
It works here @weedylan1 (7.0, Blazor Server) ...

![image](https://user-images.githubusercontent.com/1622880/235891121-3c4244b1-25a8-4df6-9b7b-d8a9641ecc88.png)

I'll close because your report doesn't include enough information to remark on. However, I would like to fix the SDK remark. This issue will close automatically when the PR merges in a few minutes.

**Comment by weedylan1** [comment] 2023-05-03 12:13
Hi Luke, the code under Blazor Webassembly is incorrect, the Program.cs is
not correct for WebAssembly.

 the Server code also has 2 issues, firstly the SignalR imports, which
someone experienced should be able to work out.

the main issue on the Blazor Server code is in the OnInitializedAsync()
method, that code will fail because of the StateHasChanged call.

this will return.

{"The current thread is not associated with the Dispatcher. Use
InvokeAsync() to switch execution to the Dispatcher when triggering
rendering or component state."}

change it to something like

protected override async Task OnInitializedAsync()
    {
        if (hubConnection == null)
        {
            hubConnection = new HubConnectionBuilder()
                .WithUrl(Navigation.ToAbsoluteUri("/chathub"))
                .Build();

            hubConnection.On<string, string>("ReceiveMessage", (user,
message) =>
            {
                var encodedMsg = $"{user}: {message}";
                messages.Add(encodedMsg);
                try
                {
                    InvokeAsync(Refresh);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            });

            await hubConnection.StartAsync();
        }
    }
    private async Task Refresh()
    {
        StateHasChanged();
    }

Please modify the example and update the WebAssembly version especially.

Kind Regards

Dan

**Comment by BrennanConroy** [comment] 2023-05-03 20:34
> Can you assist with this part of the issue?

No. I don't know blazor very well.
@MackinnonBuck maybe?

**Comment by guardrex** [comment] 2023-05-03 21:05
@MackinnonBuck ... If you want to work an issue on the PU repo for whatever the problem is, I can work on the `Program.cs` versioning problem off of this issue. @weedylan1 can open a PU issue for the error ...

> The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

I don't get that error here with the code that we're showing. The sample app runs fine AFAICT.

**Comment by guardrex** [comment] 2023-05-03 21:21
@weedylan1 ... I just checked and the `Program.cs` content is correct ...

https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Server/Program.cs

Do you mean that you think the entire file is shown? That's not the case per the article text. It leads into the code with (emphasis added) ...

> ***In*** `Program.cs` ...

This code is only meant to show the relevant part of `Program.cs` where the updates are applied. The text instructions are to that effect, namely to add the Response Compression Middleware at the top of the processing pipeline and where to add the hub. I feel good about leaving this content in its current form. If I receive more feedback asking for a change, I'll try a version that refers to the locations of added lines by their adjacent lines.

WRT your "imports" remark, I don't have anything actionable at this point. You didn't explain what was confusing. The packages and namespaces are called out, and there are no changes to the app's default `_Imports.razor` file.

**Comment by MackinnonBuck** [comment] 2023-05-03 22:49
@guardrex Thanks for looking into this! I think it's fine if we close this out, since there doesn't seem to be a problem either in the docs or in the product.

**Closed** 2023-05-03 22:50 UTC
Labels: Pri1, Source - Docs.ms, SignalR, Blazor, needs-more-info

**Comment by guardrex** [comment] 2023-05-03 23:00
cc: @bradygaster ... I just noticed that that error reported here by @weedylan1 for the Blazor-SignalR tutorial is related to something we discussed a while back on ...

https://github.com/dotnet/AspNetCore.Docs/issues/25584

... that led to wrapping the call to `StateHasChanged` in `InvokeAsync`.

@weedylan1 is reporting the persistence of the error that you called out ...

> The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

... but I can't reproduce it here. The code for the example can be seen at ...

https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorServerSignalRApp/Pages/Index.razor#L47

I'm going to leave this issue closed for the time being, and I'll re-open it if you let me know that additional investigation/work should take place.

**Comment by MmMapIoSpace** [comment] 2024-07-11 18:23
Why on Hub ( /ChatHub ) the value of Context.USer.Identity is always be null on Server mode, i want to make private chatt app that target to specified user account, it's work on Web Assembly with Persistent Authentication State, but on Blazor server the value of user identity is always null, and no chance to send the message directly to specified user account

**Comment by guardrex** [comment] 2024-07-11 18:48
@MmMapIoSpace ... We don't work on closed issues/PRs. You should open a new issue, and it sounds like in this case that you need some product support. Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

They'll probably need a minimal GitHub repro project cross-linked in your issue so that they can see your code.

Please add the following to the bottom of your opening comment so that I can follow the discussion:

```
cc: @guardrex 
```

If it turns out that we're missing some documentation, I'll open a new documentation issue to address it after I see how your support issue goes.
