### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dimaaan** [dotnet/AspNetCore.Docs#21597] opened 2021-02-21 14:57 UTC
>  Custom policy provider - IAuthorizationPolicyProvider

Link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82950389-524e-0754-a125-addeccbdb1b3
* Version Independent ID: 80b7f7cf-dc2e-137a-5aa7-fa88da63ac80
* Content: [Authentication samples for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/samples?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2021-02-21 17:33
Thanks @dimaaan ... It was moved to ...

https://github.com/dotnet/aspnetcore/tree/main/src/Security/samples/CustomPolicyProvider

... I'll patch that link real quick. 🏃

**Comment by guardrex** [comment] 2021-02-21 17:36
... there will be a short 🤞 delay on merging it. There's a regression in the docs build system. As soon as that's resolved, we'll get this link fix merged.

**Comment by guardrex** [comment] 2021-02-21 17:57
Actually, Rick, it's best if you reason on this one because the links aren't for the latest release.

Here's the link to this one for 3.1 if you intend to not point these links at the `main` branch with a note on versioning ...

https://github.com/dotnet/aspnetcore/tree/release/3.1/src/Security/samples/CustomPolicyProvider

**Comment by Rick-Anderson** [comment] 2021-02-21 22:06
Let's point to main. Anyone smart enough to figure out these samples is smart enough to find the version specific code.

**Comment by guardrex** [comment] 2021-02-21 22:07
Do you want me to do it? I am actually just kind'a sitting here not doing all that much.

**Closed** 2021-03-04 03:13 UTC
Labels: P0, Source - Docs.ms, doc-bug
