### ISSUE TITLE
Add missing 'type URI' step in POST section

### ISSUE THREAD

**Issue by andrewdove** [dotnet/AspNetCore.Docs#18834] opened 2020-06-17 19:30 UTC
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#test-posttodoitem-with-postman missing a step to add the URI. The student is left to spot its omission from the diagram that follows having clicked 'send' prematurely.

Specifically, after "Set HTTP method to POST" a step "Type the URI https://localhost:5001/api/TodoItem"

HTH
Andrew
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2020-06-17 19:59
Duplicate of #16901

**Closed by Rick-Anderson** 2020-06-17 19:59 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
