### ISSUE TITLE
Dialog does not show in Visual Studio

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#15707] opened 2019-11-15 18:27 UTC
Hi team, 
I moved this from here: https://github.com/aspnet/AspNetCore.Docs.de-de/issues/60

@atomroflman commented yesterday
In the section: Add the SignalR client library
You say: "In Solution Explorer, right-click the project, and select Add &gt; Client-Side Library" wich brings me to the libman.json instead of the shown dialog.

Betriebsystemname Microsoft Windows 10 Pro
Version 10.0.18362 Build 18362

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by paulghodgson** [comment] 2019-11-30 11:46
When I had this it was because I was selecting "Manage Client Side Libraries..." from the context menu rather than navigating to Add->Client-Side Library". It does feel like the two should both open the the dialog box.

**Comment by wadepickett** [comment] 2020-04-28 03:26
I reviewed in case the instructions could be any clearer, but they are clear.  The issue is related to product design and expectations, but it is not a common issue.  Closing this.  Thanks for bringing it up however.

**Closed by wadepickett** 2020-04-28 03:26 UTC
Labels: P1, SignalR, Source - Docs.ms, doc-bug
