### ISSUE TITLE
missing closing tag for container div.

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#27952] opened 2022-12-21 14:20 UTC
Just a little thing.  
Missing your closing div tag for the container div.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by guardrex** [comment] 2022-12-21 14:55
Hi @smiller7812 ... Can you post a screenshot of it?

**Comment by guardrex** [comment] 2022-12-21 14:57
This is what I see ...

![image](https://user-images.githubusercontent.com/1622880/208934841-8c85e7d6-1fd9-4a73-a86f-4d2890d8368b.png)

**Comment by guardrex** [comment] 2022-12-21 14:59
I'm going to close this because I don't see what the problem is. Please post a screenshot if I'm missing it.

**Comment by guardrex** [comment] 2022-12-21 15:34
Oooooh ... yeah ... I see what you mean ... a completely missing container div. Gotcha! 😄

**Closed** 2022-12-21 20:44 UTC
Labels: Pri3, Source - Docs.ms, SignalR, doc-enhancement
