### ISSUE TITLE
ASP.NET MVC with EF Core Tutorial: Implement inheritance

### ISSUE THREAD

**Issue by eproft** [dotnet/AspNetCore.Docs#22047] opened 2021-04-13 18:44 UTC
In the SchoolContext.cs file, it is necessary to remove the Student and Instructor entities from the OnModelCreating method; otherwise, an error is generated, "Invalid object name '[Entity Name]'. at Microsoft.Data.SqlClient.SqlCommand." when either the Students or Instructors navigation link is clicked.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-04-13 23:13
duplicate of #17465

**Closed by Rick-Anderson** 2021-04-13 23:13 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
