### ISSUE TITLE
Document blazor startup mode and configuration options

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#14134] opened 2019-09-04 09:33 UTC
Document the following
* Manually starting the blazor application.
* How to configure the rendered html links with the `base` tag inside `head` so that all your links work independent of the entry point url `(for example when rendering from a non default page/controller)`
* Logging options for troubleshooting
* Advanced configuration knobs:
  * Signalr config.
  * Reconnection behavior.

**Comment by guardrex** [comment] 2019-09-04 12:09
Point 1 is covered at: https://docs.microsoft.com/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#configure-the-signalr-client-for-blazor-server-side-apps

Point 2 is covered in *Hosting and deployment*, and an in-progress PR is in development to update the coverage at https://github.com/aspnet/AspNetCore.Docs/pull/13898, which will improve the current `<base>`/app base path coverage.

Point 3 is possibly a duplicate of [Troubleshoot Blazor topic (aspnet/AspNetCore.Docs \#10746)](https://github.com/aspnet/AspNetCore.Docs/issues/10746), which is on hold for the time being.

Point 4 is covered (thus far; perhaps there's more to add) at https://docs.microsoft.com/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#server-side

**Comment by javiercn** [comment] 2019-09-04 12:17
@guardrex Sorry if I was not clear. These requests are specifically for server-side blazor. As people render components apps from views like "/MyController/MyView" and don't put the base path on the view when rendering the components, and that cause the app to fail and for them to log issues.

**Comment by guardrex** [comment] 2019-09-04 12:33
I see what you u mean: App base path is only covered in hosting contexts. It will be helped a bit by the work on that current PR, which I plan to at least extend to cover both client- and server-side hosting scenarios.

The links I show for Points 1 and 4 are in the server-side coverage (*Hosting Models* topic) for those concepts, but I wouldn't be surprised if more work is needed.

**Comment by javiercn** [comment] 2020-02-03 09:39
We should have a section specific to configuring reconnection behavior on the client. See https://github.com/dotnet/aspnetcore/issues/18740#issuecomment-581321532 for details

**Comment by guardrex** [comment] 2020-07-10 19:27
Javier, I'm going to close this on the basis of:

* Updates performed on prior PRs.
* Work going in now on https://github.com/dotnet/AspNetCore.Docs/pull/19172.
* [Existing app base path coverage](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&tabs=visual-studio#app-base-path) combined with the updates on PR https://github.com/dotnet/AspNetCore.Docs/pull/19131.

If there was still something left, let me know here, and I'll open one or more new issues for whatever is left.

**Closed by guardrex** 2020-07-10 19:27 UTC
Labels: Blazor, P1, PU, area-blazor, doc-enhancement

**Comment by raphadesa** [comment] 2021-07-21 09:18
Hello team !

The fact of disconnecting mobile users after 15 seconds of inactivity is pretty annoying...

Why doesn't mobile apps behave as desktop apps ?

Any workaround ? Maybe it will be fixed in .NET 6 ?

Many thanks !

Raphaël
