### ISSUE TITLE
WASM runtime in the .NET 8 enables EH and SIMD instructions by default.

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/AspNetCore.Docs#30151] opened 2023-08-25 09:28 UTC
WASM runtime in the .NET 8 enables EH and SIMD instructions by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa3e99ba-cbe1-e8a1-6628-9b6eb39710a4
* Version Independent ID: dd777362-b92d-cac6-2343-a7aaf31d0bdf
* Content: [Tooling for ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0)
* Content Source: [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tooling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2023-08-25 09:43
@pavelsavara ... I think this is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/28996, which was resolved by https://github.com/dotnet/AspNetCore.Docs/pull/28997.

The live content is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=windows#net-webassembly-build-tools

btw ... to track .NET 8 Blazor doc work, I have an issue every year that shows where I'm at with everything ...

https://github.com/dotnet/AspNetCore.Docs/issues/28161

I'll close as completed, but let me know if more work needs to be done.

**Comment by guardrex** [comment] 2023-08-25 09:47
For ...

> .NET 8 enables EH and SIMD instructions by default.

... we might need to update it after all. It currently tells devs that ...

> To enable WebAssembly exception handling, use the <WasmEnableExceptionHandling> property in the app's project file (.csproj) with a value of true:

... and shows the MS Build config.

Should that be removed for >=8.0?

**Comment by guardrex** [comment] 2023-08-25 09:49
Yes, I think that's right. Also, since it's enabled by the default the guidance should be showing how to ***disable*** it for >=8.0, so I'll change that section and ping u on the PR. Currently, it states in the text that it's enabled by default but still shows the setting to `true`.

I'll fix it now and ping u on the PR.

**Comment by pavelsavara** [comment] 2023-08-25 09:49
You may need to switch it off, for example when you are targeting old/mobile devices.
Here are details on how https://github.com/dotnet/runtime/blob/main/src/mono/wasm/features.md#simd---single-instruction-multiple-data

**Comment by pavelsavara** [comment] 2023-08-25 09:52
And note it's broken right now https://github.com/dotnet/runtime/issues/89302

**Closed** 2023-08-25 11:43 UTC
Labels: Pri1, Blazor, doc-enhancement, 8.0
