### ISSUE TITLE
Weboptimizer is not compatible 

### ISSUE THREAD

**Issue by LoupaLoupa** [dotnet/AspNetCore.Docs#28191] opened 2023-01-25 15:08 UTC
[Enter feedback here]
Weboptimizer is not compatible with anything newer than dotnet core  3.0, please remove links to it as I have lost many hours looking into that solution. Also, why can't we have these solution in dotnet directly, it seem like basic services.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-7.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2023-01-25 15:58
Hello @LoupaLoupa ... This is a duplicate of #20808.

**Closed by guardrex** 2023-01-25 15:58 UTC
Labels: Source - Docs.ms, :watch: Not Triaged

**Comment by LoupaLoupa** [comment] 2023-01-25 16:11
OK, so please remove links from the dotnet 6 and 7 documentation, this is confusing and unnecessary time sinks.

Thank you
