### ISSUE TITLE
bind get, set, after can't be used in 7.0 Blazor applications

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/AspNetCore.Docs#27848] opened 2022-12-06 16:33 UTC
See https://github.com/dotnet/core/blob/main/release-notes/7.0/known-issues.md#70-bind-get-set-after-cant-be-used-in-70-blazor-applications

Notes should be added to the documentation. It's very frustrating when the code samples in the documentation don't work. Any potential workarounds such as rolling back to preview/RC versions and any trackable issues should also be included.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-12-06 16:37
Hello @MisinformedDNA ... First I've heard of this. Word didn't reach me that there was a problem.

@danroth27 @mkArtakMSFT ... Would you like merely a NOTE until 7.0.1 (if it's soon, for example), or do you want me to comment-out the content until 7.0.1 release?

**Comment by guardrex** [comment] 2022-12-06 19:22
Ok, @MisinformedDNA ... I got word back offline. They are trying to get this fixed for 7.0.1, the December release, and we should know about that fix landing in a week or so. I've been instructed to just hold here for a week and not update the guidance but merely respond to any issues that come in on it. If it doesn't make the December release, the fix will be in the January release, and then ***Yes!*** ... we need a NOTE in the topic and in the *What's New* guidance on this.

Leave this issue open. I'll monitor things and see where we stand next week if that's when 7.0.1 lands.

**Comment by danroth27** [comment] 2022-12-06 19:37
Yes, this is an unfortunate [known issue](https://github.com/dotnet/core/blob/main/release-notes/7.0/known-issues.md#70-bind-get-set-after-cant-be-used-in-70-blazor-applications) with the initial .NET 7 release. It will be fixed in an upcoming patch release. I believe the patch will be available in about a week. I think adding a note about the issue and the patch in the related section makes sense.

**Comment by guardrex** [comment] 2022-12-06 19:44
Thx @danroth27 ... Artak said to wait a week, but a NOTE is quick-'n-easy to add now and pull later, so I'll go ahead and take care of it and take it live right now.

**Comment by joshgreenwald** [comment] 2022-12-13 21:04
So it looks like bind:after compiles and executes, but Visual Studio 17.4.3 and 17.5 Preview 2.0 still underline the bind:after attribute in red and show the same error. Definitely an improvement but confusing.  😆

**Comment by iphdav** [comment] 2022-12-13 23:20
I am tracking this in my original issue here: https://github.com/dotnet/aspnetcore/issues/44957

There is confusion because the InputNumber, InputText (etc) do work and have worked since 7.0.0.  The problem is with the input controls.  I confirm the bug persists in 7.0.1 and SDK 7.0.101 and even when compiling from the command line using dotnet build the compiler error still occurs.  I cannot see anything has been fixed in 7.0.1 / 7.0.101 when compiling from the command line using dotnet build.

@guardrex and @danroth27, I strongly suggest we make this very prominent in the documentation that this feature did not ship with .NET 7 in a fully working state.  We are now on the first patch release and it is still not working and anyone watching the dotnet conf videos or reading the documentation will be confused.  My assumption is best case scenario would be a fix around late Jan or Feb now as we are going into the holidays?

Suggest people use the InputNumber, InputText controls as a work around until this gets resolved.

**Comment by guardrex** [comment] 2022-12-13 23:26
Thanks @iphdav ... I'll chat with Dan about this offline (unless he sees this first and responds here) and get back to you.

**Comment by iphdav** [comment] 2022-12-13 23:39
@guardrex I also just realised the reason everyone is confused (about if anything was fixed) is because some fixes clearly did come through for blazor wasm, where things are still broken for blazor server.  This is why every second person is saying "It is broken still" then the next comment is "it is working now".  I am using blazor server and I am *not* seeing the fixes people using blazor wasm are reporting.

**Comment by guardrex** [comment] 2022-12-14 01:01
@iphdav ... I've received word back that this is under investigation with the patch release, and I see that Dan is discussing it with you further on your PU issue right now. I'll temporarily update the existing NOTEs tomorrow (Wednesday) morning. There's no need to post updates here. I'll keep an 👁️ on things over the next few days.

**Closed** 2023-03-15 20:12 UTC
Labels: Pri1, Source - Docs.ms, Blazor
