### ISSUE TITLE
Scaffold the movie model , not working for visual studio for Mac

### ISSUE THREAD

**Issue by markmnyc** [dotnet/AspNetCore.Docs#29200] opened 2023-05-07 18:01 UTC
Scaffolding not working as per documentation ,

Item 2 , Control-click on the Pages/Movies folder > Add > New Scaffolding.... 

errors out with : DbContextOptionsBuilder does not contain a definition for 'UseSqlite' , even though during the scaffolding it adds the package in visual studio for Mac . perhaps it would be a good idea to add that if this happens we should provide the package add for sql lite that will fix it to not hold the user back ? 

for me the solution was Install-Package Microsoft.EntityFrameworkCore.Sqlite

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment] 2023-05-08 05:06
@markmnyc, thanks for the heads up.  I am actually working on updating this series this sprint.  There were changes in scaffolding tooling lately.  You are correct, the doc is not working as is and needs an update.  Closing since this is a dupe of #28992.  
Noting this one as also related to the work for #28668 and #29052.

**Closed by wadepickett** 2023-05-08 05:06 UTC
Labels: Source - Docs.ms
