### ISSUE TITLE
Allow subscribing to page updates via RSS or ATOM

### ISSUE THREAD

**Issue by loligans** [dotnet/AspNetCore.Docs#17662] opened 2020-04-07 19:59 UTC
I would like to subscribe to page updates via RSS or ATOM feed readers. That way I can know immediately when changes occur and have an organized reference to when and what changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8bd1b6-c7a4-712b-7a79-f5c4a309f2a6
* Version Independent ID: a6bee3a9-7548-d91a-2794-82becf9f3a89
* Content: [ASP.NET Core docs: What's new for March 2020](https://docs.microsoft.com/en-us/aspnet/core/whats-new/2020-03?view=aspnetcore-3.1)
* Content Source: [aspnetcore/whats-new/2020-03.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/whats-new/2020-03.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-whatsnew**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment] 2020-04-08 04:46
I think that would need to be decided at a higher level.

cc @scottaddie

**Comment by scottaddie** [comment] 2020-04-08 17:57
Closing as a duplicate of https://github.com/MicrosoftDocs/feedback/issues/1116. Feel free to discuss further in that issue. This is a site-wide feature that engineering would need to prioritize.

**Closed by scottaddie** 2020-04-08 17:57 UTC
Labels: Source - Docs.ms, doc-idea, needs-more-info
