### ISSUE TITLE
RegisterAsCustomElement was renamed to RegisterCustomElement

### ISSUE THREAD

**Issue by floreseken** [dotnet/AspNetCore.Docs#26470] opened 2022-07-19 20:10 UTC
Looks like in the 7.0 (preview 6) version of the CustomElements package `RegisterAsCustomElement` was renamed to `RegisterCustomElement`

![image](https://user-images.githubusercontent.com/6927344/179838439-f448a8f6-19be-4738-889e-698b623aab42.png)

![image](https://user-images.githubusercontent.com/6927344/179838497-03183131-2b27-4746-8a1c-afc144f69518.png)

See source here: https://github.com/dotnet/aspnetcore/blob/main/src/Components/CustomElements/src/JSComponentConfigurationExtensions.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-07-21 11:00
Just discovered that this is a duplicate of an existing tracking item for .NET 7 on the tracking issue at https://github.com/dotnet/AspNetCore.Docs/issues/26364.

**Closed by guardrex** 2022-07-21 11:00 UTC
Labels: P1, Source - Docs.ms, Blazor, doc-enhancement, 7.0
