### ISSUE TITLE
Configuring Stateful Reconnect

### ISSUE THREAD

**Issue by CePur** [dotnet/AspNetCore.Docs#31452] opened 2024-01-15 16:31 UTC
### Description

[[Enter feedback here]](https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-8.0&tabs=dotnet#configure-stateful-reconnect) 

Hi, trying stateful reconnect but js throws this exception
"(intermediate value).withUrl(...).withStatefulReconnect is not a function". Using https://unpkg.com/browse/@microsoft/signalr@8.0.0/

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-8.0&tabs=dotnet#configure-stateful-reconnect

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/configuration.md

### Document ID

66d252c3-6300-7e28-9aa0-ef2ff66e7a76

### Article author

@bradygaster

---
[Associated WorkItem - 226929](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226929)

**Comment by wadepickett** [comment] 2024-01-15 20:57
@CePur, thanks for taking the time to let us know your experience with this doc.
I will cue this doc up to be retested.  In the meantime, it would be good to verify the following isn't happening that could result in that error:
Take a look at the .csproj file of your project and note if you are still referencing an old `Microsoft.AspNetCore.SignalR.Client.Core`.   There should not be one in there.  Instead, it should be `Microsoft.AspNetCore.SignalR.Client` and it should be the latest version you were already mentioning.  Please let me know if that turns out to be what was happening.  Thanks again!

**Comment by CePur** [comment] 2024-01-16 08:44
@wadepickett i don't directly reference it so there is no Microsoft.AspNetCore.SignalR.Client in .csproj. Project is asp.net web project `<Project Sdk="Microsoft.NET.Sdk.Web">` targeting net8.0

**Comment by wadepickett** [comment] 2024-01-16 19:22
Thanks for the insight!

**Comment by wadepickett** [comment] 2024-03-27 00:22
@BrennanConroy

With the following set in Program.CS for stateful reconnect:
`builder.Services.AddSignalR(o => o.StatefulReconnectBufferSize = 1000);`

and

`app.MapHub<ChatHub>("/chatHub", options =>
{
    options.AllowStatefulReconnects = true;
});`


Should the client example in config be this the following using `.withAutomaticReconnect`?
`var connection = new signalR.HubConnectionBuilder()
    .withUrl("/chatHub")
    .withAutomaticReconnect()
    .build();`

The example we had in there for a JavaScript Client was the following:
`const builder = new signalR.HubConnectionBuilder()
  .withUrl("/hubname")
  .withStatefulReconnect({ bufferSize: 1000 });  // Optional, defaults to 100,000
const connection = builder.build();`

But that example does indeed result in a runtime error that does not recognize `withStatefulReconnect` as a function:
`TypeError: (intermediate value).withUrl(...).withStatefulReconnect is not a function`

I'll update the doc but honestly I'm not sure what the correct client setting should be.

**Comment by wadepickett** [comment] 2024-03-28 16:35
@BrennanConroy, I'm hoping you might be able to take a look a this above.  I would have to get the fix in today to get a review in time for this sprint.  Sorry to ask, I looked through the source and all related issues and the end result SignalR.js. I'm not able to get it to work as intended.

**Comment by BrennanConroy** [comment] 2024-04-01 03:05
The function does exist, look at line 3474 of https://unpkg.com/browse/@microsoft/signalr@8.0.0/dist/browser/signalr.js

I'm guessing they aren't using an 8.0 version of the library.

**Comment by wadepickett** [comment] 2024-04-05 18:51
Thanks @BrennanConroy.  Could you check a new download through the VS libman using  unpkg for browser/signalr.js for 8.0.0 or "latest"?  I see it on the unpkg site as you pointed out.  However, when I add it through Visual Studio using the Library Manager for unpkg and I either specify "latest" or "8.0.0" I receive a version that does not have the word "stateful" anywhere in browser/signalr.js

![image](https://github.com/dotnet/AspNetCore.Docs/assets/10985336/d241f584-7294-434e-a249-e60d5cb8dbdf)

Here is what lines 1177 - 1179 should have in it:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/10985336/d76d9382-bb73-4c5d-b803-6eecbb00f156)

The downloaded 8.0.0 signalr.js however is missing the const for DEFAULT_STATEFUL_RECONNECT_BUFFER_SIZE:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/10985336/84321a6f-28d9-4508-96df-c1a42defa584)

withServerTimeout(), withKeepAliveInterval() and withStatefulReconnect()should be defined right after withAutomaticReconnect() starting on line 3456 through 3481.  
However, in the downloaded 8.0.0 signalr.js through libman for unpkg,  those 3 are missing.  After withAutomaticReconnect() is defined, then comes build() right after:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/10985336/4518b491-300f-4ca8-b6a6-b3850dd06285)

Should I file a tracking issue?  Maybe it is cache issue on unpkg for 8.0.0 or it was not propagated across all their servers?

I checked I also checked jsdelivr, that service for 8.0.0 is fine, withStatefulReconnect and the other new functions are in there as expected.

**Comment by BrennanConroy** [comment] 2024-04-05 18:56
> Could you check a new download through the VS libman using unpkg for browser/signalr.js for 8.0.0

Just tried, it has the stateful reconnect code.

**Comment by wadepickett** [comment] 2024-04-05 19:09
Interesting.  I must be doing something goofy on this end.  I get 8.0.0 for jsdelivr just fine, for unpkg 8.0.0 shows up selectable and downloads, but the actual download that arrives is a version before 8.0.0 without stateful reconnect.  I started with new projects each test and reboot VS.  I have the latest VS.  This issue is just for unpkg for me when using libman on VS.

Maybe I am getting a particular server on the farm for unpkg and re-hitting it?  That seems slim though, so must be something I am missing on my end given you are not able to recreate.  Thanks.

**Comment by wadepickett** [comment] 2024-04-05 19:13
Closing since not a doc issue to update here after testing it out.

**Closed by wadepickett** 2024-04-05 19:13 UTC
Labels: Source - Docs.ms, seQUESTered

**Comment by CePur** [comment] 2024-04-30 17:34
I believe i found the issue. For future wanderers:

https://github.com/aspnet/LibraryManager/issues/640#issuecomment-2086157971

**Comment by wadepickett** [comment] 2024-05-01 04:10
Awesome, thanks @CePur!
