### ISSUE TITLE
The article does not seem to be updated for .NET 6

### ISSUE THREAD

**Issue by ahelland** [dotnet/AspNetCore.Docs#26135] opened 2022-06-13 18:54 UTC
[Enter feedback here]
If one has installed .NET 6 this article may be confusing for the reader as it seems to be written for .NET 5. (Even though the version selector indicates "Core 6.0". The article prereqs has the disclaimer that .NET 5 or later is needed, so one might figure .NET 6 was not in scope originally if one runs into issues.)

Examples:
"In Views/Shared, create a file named _LoginPartial.cshtml. Include the following code". 
Scaffolding the code with .NET 6 creates a folder called "Pages/Shared".

"In Startup.cs, make the following changes"
With .NET the default is to not use Startup.cs and use Program.cs instead:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-6.0

The code needed for adding auth is similar so it's possible to figure out, but one cannot follow the steps exactly as described with the newest bits installed :) 

Let me know if you'd prefer having me submit a PR with the necessary changes for .NET 6 to resolve the issue.

#ATCP
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by guardrex** [comment] 2022-06-13 19:48
Hi @ahelland ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/23287.

**Closed by guardrex** 2022-06-13 19:48 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
