### ISSUE TITLE
Possible Code Example Error on SignalR Hubs Page

### ISSUE THREAD

**Issue by epikkoder** [dotnet/AspNetCore.Docs#30422] opened 2023-09-20 18:41 UTC
On the first code example under the "Client results" of the "Use hubs in SignalR for ASP.NET Core" page, using this same code on Visual Studio gives me the CS1501 error `No overload for method 'InvokeAsync' takes 1 arguments`. I would have to add the `CancellationToken` argument for it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0#client-results)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment] 2023-09-20 18:46
Dupe of https://github.com/dotnet/AspNetCore.Docs/issues/27996

**Comment by wadepickett** [comment] 2023-09-20 19:23
Closing this dupe and raising #27996 as a priority.  Thanks.

**Closed by wadepickett** 2023-09-20 19:23 UTC
Labels: Source - Docs.ms, SignalR
