### ISSUE TITLE
Outdated Angular version

### ISSUE THREAD

**Issue by ricfwolff** [dotnet/AspNetCore.Docs#22487] opened 2021-06-03 12:17 UTC
Some ideas that might help other beginners like me:

I noticed that the template for Angular app created through Visual Studio (and dotnet cli) will give me Angular version 8. It's already two years old (which, for Angular, seems to be a lot).
Why don't you create a simpler "blank" template, with just an Angular's latest version page being served by the server and that's it?

I'm new to Angular and I wanted to test it with the latest version. But I lost a whole day updating angular to the latest version and fixing weird errors that appear during this process. Not knowing which packages I can remove and which ones are essential...

And why is there a back-end? Why not just serve the angular project as static files? Wouldn't that be simpler? Since most devs will have to communicate to an external API, we don't need back-end for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by Rick-Anderson** [comment] 2021-06-04 05:02
Duplicate of #18074

**Closed by Rick-Anderson** 2021-06-04 05:02 UTC
Labels: :watch: Not Triaged, Source - Docs.ms

**Comment by MackinnonBuck** [comment] 2022-11-01 21:31
> I noticed that the template for Angular app created through Visual Studio (and dotnet cli) will give me Angular version 8. It's already two years old (which, for Angular, seems to be a lot).

We've since updated the Angular version and now do so on a regular basis (we're currently on Angular 14 at the time I'm writing this comment).

> And why is there a back-end? Why not just serve the angular project as static files? Wouldn't that be simpler? Since most devs will have to communicate to an external API, we don't need back-end for that.

The purpose of the template is to be ASP.NET Core hosted. If you want .NET out of the picture, you can create a new Angular project using the [Angular CLI](https://angular.io/tutorial/toh-pt0).

---

AFAICT, there aren't any docs-related actions that need to be taken here.
