### ISSUE TITLE
Modify nginx proxy_pass address

### ISSUE THREAD

**Issue by FatTigerWang** [dotnet/AspNetCore.Docs#21953] opened 2021-04-01 10:20 UTC
***Google translate***
In the Nginx configuration section, it is recommended to proxy_pass http://localhost:5000 modify it to proxy_pass http://127.0.0.1:5000, because the proxy localhost will cause nginx simultaneous proxying IPv6, and currently many applications (especially local applications that require proxy) will only listen to the IPv4address, so you will nginx see this error in the error log:

```txt
 [error] 2195#0: *2645 connect() failed (111: Connection refused) while connecting to upstream, client: ipaddress, server: domain, request: "GET /path HTTP/1.1", upstream: "http://[::1]:5000/path", host: "domain", referrer: "domain"
```

You can see that Nginx the local IPv6 port is proxied and an error is displayed: 
`upstream: "http://[::1]:5000/path"`

 ---------
Original

在[配置 Nginx](https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx)部分，建议将`proxy_pass         http://localhost:5000`修改为`proxy_pass         http://127.0.0.1:5000`，因为代理`localhost`会导致`nginx`同时代理`IPv6`，而目前很多应用（特别是需要代理的本地应用）只会监听在`IPv4`地址，因此，会在`nginx`的错误日志中看到此错误：
```txt
 [error] 2195#0: *2645 connect() failed (111: Connection refused) while connecting to upstream, client: ipaddress, server: domain, request: "GET /path HTTP/1.1", upstream: "http://[::1]:5000/path", host: "domain", referrer: "domain"
```
可以看到`Nginx`代理了本机`IPv6`端口并显示错误：`upstream: "http://[::1]:5000/path"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [使用 Nginx 在 Linux 上托管 ASP.NET Core](https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-04-01 18:24
@halter73  please review

**Comment by guardrex** [comment] 2021-04-01 18:24
Duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/21944.

**Comment by guardrex** [comment] 2021-04-01 18:25
... there's a PR, too, attached to that other one. I pinged Sourabh to look :eyes:.

**Closed** 2021-04-01 18:37 UTC
Labels: Source - Docs.ms, needs-more-info
