### ISSUE TITLE
5.0 update: Use ASP.NET Core APIs in a class library

### ISSUE THREAD

**Issue by PoisnFang** [dotnet/AspNetCore.Docs#20574] opened 2020-11-14 08:17 UTC
Shouldn't this page be updated to explain how this works in .NET 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98629146-7d64-9f48-6e45-51bafe8c7116
* Version Independent ID: cdb2b89f-bf1c-f313-0062-7f6b7ef8b611
* Content: [Use ASP.NET Core APIs in a class library](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/target-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/target-aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment] 2021-05-11 00:57
Duplicate of #21725

**Closed by Rick-Anderson** 2021-05-11 00:57 UTC
Labels: Source - Docs.ms, doc-enhancement

**Comment by PoisnFang** [comment] 2021-05-11 03:37
@Rick-Anderson Technically #21725 is a duplicate of this one, semantics really, but I digress haha.
