### ISSUE TITLE
.NET 7: Kestrel support for WebSockets over HTTP/2

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26545] opened 2022-07-25 23:55 UTC
[Kestrel support for WebSockets over HTTP/2](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#kestrel-support-for-websockets-over-http-2)

**Comment by tdykstra** [comment] 2022-09-08 21:42
Closing as duplicate of #26366

**Closed by tdykstra** 2022-09-08 21:42 UTC
Labels: 7.0
