### ISSUE TITLE
'Id' should be removed from the TodoItemDTO class constructor

### ISSUE THREAD

**Issue by marqdouj** [dotnet/AspNetCore.Docs#23814] opened 2021-11-09 12:54 UTC
The TodoItemDTO class constructor takes an 'Id' parameter:

`public TodoItemDTO(Todo todoItem) =>
    (Id, Name, IsComplete) = (todoItem.Id, todoItem.Name, todoItem.IsComplete);`

The constructor should be changed to:

`public TodoItemDTO(Todo todoItem) =>
    (Name, IsComplete) = (todoItem.Name, todoItem.IsComplete);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-11-09 16:35
Duplicate of #23803

**Closed by Rick-Anderson** 2021-11-09 16:35 UTC
Labels: Source - Docs.ms, doc-bug
