### ISSUE TITLE
localization with Blazor Hybrid

### ISSUE THREAD

**Issue by ErikApption** [dotnet/AspNetCore.Docs#26579] opened 2022-07-28 17:44 UTC
Any chance to add some notes about localization with Blazor Hybrid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Version Independent ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Content: [Build a .NET MAUI Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/maui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/maui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-07-28 17:49
Hello @ErikApption ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/25679.

**Closed by guardrex** 2022-07-28 17:49 UTC
Labels: Source - Docs.ms, Blazor
