### ISSUE TITLE
Kestrel sample update to 5.0

### ISSUE THREAD

**Issue by joancafom** [dotnet/AspNetCore.Docs#20836] opened 2020-12-02 11:50 UTC
[EDIT by guardrex to add the metadata]

**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
`kestrel, 5.0, sample, servers`

- Tell us what docs you found that didn't address your concern.
https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md

**Describe the new topic**

- Explain why this topic is needed.
As you provide samples for `2.X` and `3.X` (take), it would be a good idea to support `5.X` as well.

- Suggest a location in the Table of Contents.
NA.

- Write an abstract. In one **short** paragraph, describe what this topic will cover.
The current release of .NET version `5.0` does not seem to be compatible with any of the Kestrel Samples available in the repository (see [ref](https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/servers/kestrel/samples)), resulting in the following error:

    ```bash
    It was not possible to find any compatible framework version
    The framework 'Microsoft.AspNetCore.App' version '3.1.0' was not found.
      - The following frameworks were found:
           5.0.0 at [/opt/aspnet-core/bin/shared/Microsoft/AspNetCore.App]

    You can resolve the problem by installing the specified framework and/or SDK.
    ```
    
    I have seen you already addressed this issue in previous versions (for instance, in https://github.com/dotnet/AspNetCore.Docs/pull/16170/). Will you also be addressing this one?

- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-12-02 11:55
For a faster response, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by joancafom** [comment] 2020-12-02 12:07
Thanks @guardrex but I can't happen to find neither the button nor the feedback section in the topic.

**Comment by guardrex** [comment] 2020-12-02 12:10
@joancafom ... 

It's here ... 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0#feedback

... but I can just answer directly ...

This topic has been continuously updated and includes known (AFAIK) any Kestrel updates that apply to 5.0 (for example, https://github.com/dotnet/AspNetCore.Docs/pull/20261).

The problem is likely in the app. Create a new app using the 5.0 SDK and compare package references and framework in the project file of the new app to your app (and/or access the migration topics, for example: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio). Also, you might want to nuke the `bin` and `obj` folders and nuke the package caches with `dotnet nuget locals --clear all`. Then restore, build, and try running your app again.

**Comment by guardrex** [comment] 2020-12-02 12:12
> neither the button nor the feedback section in the topic

Can you provide a link to the topic .... I'm curious if for some reason .... the *Feedback* section isn't showing up properly.

**Comment by joancafom** [comment] 2020-12-02 12:31
Hi @guardrex 

Thanks for your reply!

> This topic has been continuously updated and includes known (AFAIK) any Kestrel updates that apply to 5.0 (for example, #20261).

Yes you are right about the topic being updated. However, I am more precisely talking about the Kestrel Sample app that is available in this same git repository:

https://github.com/dotnet/AspNetCore.Docs/blob/d57a751df79053b27f4702503d33f4799a524a62/aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/KestrelSample.csproj#L1-L7

As per your recommended [migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio), this file should be updated to:

```diff 
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
-    <TargetFramework>netcoreapp3.1</TargetFramework>
+    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

> The problem is likely in the app.

We are using the aforementioned KestreSample app, but only entries for `2.X` and `3.X` are available:
https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/servers/kestrel/samples

**Comment by joancafom** [comment] 2020-12-02 12:32
> Can you provide a link to the topic (if not looking at the English-US version)? .... I'm curious if for some reason the _Feedback_ section isn't showing up properly.
> 
> Note: If a Feedback issue is opened for the English-US topic, it shows up here for the docs team. If a Feedback issue is opened from a non-English-US topic, it opens for the localization folks (translation issues).

Reloading the page seems to solve the issue, now it appears 🙂

**Comment by guardrex** [comment] 2020-12-02 12:33
Oh, yes ... I forgot about that. I used to work on this topic quite a bit, but others have taken it over since then because I work on Blazor topics now.

I'll add the metadata for the topic manually to this issue.

To update the sample, we usually create a new 5.x sample app. That sort of work needs to be done across the repo. I have a feeling that many, *many* sample apps are in the same boat.

**Comment by Rick-Anderson** [comment] 2020-12-02 19:38
> As you provide samples for `2.X` and `3.X` (take), it would be a good idea to support `5.X` as well.

Not enough changes from 3.1 to 5.x to warrant a new sample.
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Closed by Rick-Anderson** 2020-12-02 19:38 UTC
Labels: :watch: Not Triaged
