### ISSUE TITLE
Possible Missing NuGet package

### ISSUE THREAD

**Issue by mesMess** [dotnet/AspNetCore.Docs#31303] opened 2023-12-26 02:10 UTC
### Description

[Enter feedback here]
**Machine:**
MacBook Air, Retina, 13-inch, 2019

**OS:**
macOS Sonoma 14.2.1

**SDK:**
.NET 8.0.100

IDE:
Visual Studio Code 1.85.1 (Universal)
Commit - 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2

**Section:**
Scaffold Controller

**Command:**
"dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers"

**Expected Result/s:**
The command would generate a controller wired-up (db-context) for usage in the API

**Actual Result/s:**
When running the command the developer is met with a missing package message

**Error Output:**

_Short Output:_
To scaffold controllers and views using models, install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Tools

_Long Output:_
```
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
To scaffold controllers and views using models, install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Tools
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:12.92
```

**Resolution:**
Once the developer adds the required package they are able to move forward. Note that the missing package from the output is not mentioned in the "Learn Tutorial"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio-code

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

**Comment by guardrex** [comment] 2023-12-26 12:10
Hello @mesMess ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/31260.

**Comment by mesMess** [comment] 2023-12-30 22:25
Got it, thank you. My apologies.

**Closed** 2024-01-03 00:42 UTC
Labels: Source - Docs.ms, :watch: Not Triaged, aspnet-core/prod, aspnetcore-tutorials/tech
