### ISSUE TITLE
Signout with AuthStateProvider

### ISSUE THREAD

**Issue by mawroos** [dotnet/AspNetCore.Docs#17666] opened 2020-04-08 01:05 UTC
This documentation talks about sign in process, but no detail about how to handle sign out?
I can use httpconectextaccessor to clear the cookies, but thought there must be a way to use the new mechanism, I'm using blazor server side with Aad integration, can you provide some feedback/example on this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio&viewFallbackFrom=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-04-08 23:39
Hello @mawroos ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/15651, which deals with scaffolding Identity into a Blazor app and using it. Until I get to that issue, have a look at the notes here :point_right: https://github.com/dotnet/aspnetcore/issues/19148#issuecomment-602022059 and Javier's notes here :point_right: https://gist.github.com/javiercn/62044bab948e42cc9e4e695e4aaee7b8#considerations-with-the-app-id-uri ... especially Javier's remark in those notes [HERE](https://gist.github.com/javiercn/62044bab948e42cc9e4e695e4aaee7b8#customizing-the-sign-in-and-sign-out-processes).

**Closed by guardrex** 2020-04-08 23:39 UTC
Labels: Blazor, Source - Docs.ms, doc-enhancement
