### ISSUE TITLE
Undocumented breaking change in IFileInfo: don't use physical path anymore when serving from packfiles

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/AspNetCore.Docs#15020] opened 2019-10-11 16:48 UTC
# Issue description

When serving content from packfiles, returning the path of the packfile in IFileInfo.PhysicalPath (for filesystem watcher) doesn't work anymore.

In reading the code, I'm convinced the change is intentional.

# Software versions
- [X] .NET Core 3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1#glob-patterns)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-10-11 17:34
@jhudsoncedaron Would you mind closing this issue and re-opening it using the **This Page** feedback button at the bottom of the topic? It will tag the issue with metadata to help the team work the issue, and it automatically pings the doc author.

**Comment by jhudsoncedaron** [comment] 2019-10-11 17:36
@guardrex : Which page? The list of breaking changes is a link to an issue filter in github.

**Comment by guardrex** [comment] 2019-10-11 17:40
Sorry, I thought this was associated with a specific doc page, such as the *File Providers* page ...

https://docs.microsoft.com/aspnet/core/fundamentals/file-providers

There are also the migration page and the release notes page ...

* https://docs.microsoft.com/aspnet/core/migration/22-to-30
* https://docs.microsoft.com/aspnet/core/release-notes/aspnetcore-3.0

I'll defer to @Rick-Anderson to triage this one.

**Comment by Rick-Anderson** [comment] 2019-10-11 18:16
@jhudsoncedaron  breaking changes need to originate from https://github.com/aspnet/Announcements/issues
If it's not there, open an issue in https://github.com/aspnet/AspNetCore/issues and refer to this issue.

**Comment by maryamariyan** [comment] 2020-07-20 21:07
I'm trying to find what change caused this. @JunTaoLuo can you help me with this?

**Comment by JunTaoLuo** [comment] 2020-07-21 19:27
I'm not quite understanding what the issue here is. Specifically, what do you mean by packfile? Is this related to using the PhysicalFileProvider in aspnetcore? If that's the case, there is a bug since we still expose the physical path: https://github.com/dotnet/extensions/blob/release/3.1/src/FileProviders/Physical/src/PhysicalFileInfo.cs#L32

**Comment by maryamariyan** [comment] 2020-07-21 19:29
@JunTaoLuo I'll close this as dupe of https://github.com/dotnet/docs/issues/19562

**Comment by maryamariyan** [comment] 2020-07-21 19:29
Actually I don't have permissions :)

**Comment by maryamariyan** [comment] 2020-07-21 19:33
Same code as moved to runtime: https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileInfo.cs#L32

**Comment by maryamariyan** [comment] 2020-07-21 19:53
The only relevant change I have found since then is https://github.com/dotnet/extensions/pull/928

**Comment by jhudsoncedaron** [comment] 2020-07-21 20:25
@maryamariyan : Ah you're looking in the wrong direction. Breaking change happened between 2.1 and 3.0; see initial date of October 2019.

**Comment by maryamariyan** [comment] 2020-07-21 20:55
cc @HaoK 

Repro code: https://github.com/dotnet/docs/issues/19562#issuecomment-662061423

**Comment by Rick-Anderson** [comment] 2021-05-07 22:45
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

**Closed by Rick-Anderson** 2021-05-07 22:45 UTC
Labels: doc-bug
