### ISSUE TITLE
Customize WebApplicationFactory and ConfigureAppConfiguration

### ISSUE THREAD

**Issue by kristofferjalen** [dotnet/AspNetCore.Docs#23915] opened 2021-11-15 16:39 UTC
[Documentation](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#customize-webapplicationfactory) uses `Startup` as the entry point class of the SUT, however .NET 6 has squashed `Startup.cs` into `Program.cs`, and I don't really understand how to configure the app with a custom `appsettings.Test.json` so that values in that will be loaded before Program.cs executes:

```
// where should I put this code?

builder.ConfigureAppConfiguration((_, config) =>
{
   var appSettings = Path.Combine(Directory.GetCurrentDirectory(), "appsettings.Test.json");

   config.AddJsonFile(appSettings);
})
```

Since I don´t manage to hit the `ConfigureAppConfiguration`, below code won't have any configuration.

**Program.cs:**

```
var builder = WebApplication.CreateBuilder(args);

var foo = builder.Configuration["foo"]; // null
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-11-15 19:18
Duplicate of #23543

**Closed by Rick-Anderson** 2021-11-15 19:18 UTC
Labels: Source - Docs.ms, :watch: Not Triaged
