### ISSUE TITLE
Razor support for overloaded methods

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/AspNetCore.Docs#18543] opened 2020-05-28 18:57 UTC
[EDIT by guadrex to add the metadata. @Seabizkit, please use the **This Page** feedback button+form at the bottom of any topic to open an issue. It will automatically add the metadata and ping the author.]

overloads do not work

simple example
```
@{

    void RenderName(string name)
    {
        <p>Name: <strong>@name</strong></p>
    }

    void RenderName(int intValue)
    {
        <p>Name: <strong>@intValue</strong></p>
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-05-28 19:06
@NTaylorMullen Is this supported? It's not addressed in the Razor syntax topic?

**Comment by NTaylorMullen** [comment] 2020-05-28 19:30
> @NTaylorMullen Is this supported? It's not addressed in the Razor syntax topic.

Overloads should work. @Seabizkit what issue are you seeing with them?

**Comment by Seabizkit** [comment] 2020-05-28 21:10
@NTaylorMullen 

that complains... as is does not compile....."name already exist... compile error" but what is interesting unless i missed something... but below work... surely they should both work.
``
@functions {
 void RenderName(string name)
    {
        <p>Name: <strong>@name</strong></p>
    }

    void RenderName(int intValue)
    {
        <p>Name: <strong>@intValue</strong></p>
    }
}
``

**Comment by NTaylorMullen** [comment] 2020-05-28 21:58
> key word functions, makes it work... how odd

Ahh, interesting what you're seeing then is a C# restriction.When you say `@functions {...}` what you're saying is add the following to my class body where `@{}` entails add the following to a method in my class body (a local function). Therefore since C# doesn't support overloaded local functions you can't utilize them in `@{}`.

I can reproduce in a simple console app:
![image](https://user-images.githubusercontent.com/2008729/83198153-82ca1400-a0f3-11ea-9d9d-d9ff5fcb7b38.png)

@guardrex is there a "by design" equivalent label?

**Comment by guardrex** [comment] 2020-05-28 22:08
No, but we don't cover it in the Razor syntax topic. Would you like it covered there?

**Comment by guardrex** [comment] 2020-05-28 22:09
If we close as by-design, it can be labelled with `product-question`.

**Closed** 2020-05-28 22:14 UTC
Labels: Source - Docs.ms, doc-enhancement, product-question
