### ISSUE TITLE
Clarification needed in section prefaced by "The logger output shows:"

### ISSUE THREAD

**Issue by ebussa** [dotnet/AspNetCore.Docs#22589] opened 2021-06-22 12:40 UTC
In the bulleted section prefaced by "The logger output shows:", the meaning of the following phrase is not clear to me:

`Scoped objects are the same for each request but different across each request.`  

What is meant by the phrase "different across _each request_" as opposed to "the same for _each request_".

My guess at what was meant is "different for _each call_"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2021-06-22 12:49
Hello @ebussa ... Closing as a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/22559.

**Closed by guardrex** 2021-06-22 12:49 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
