### ISSUE TITLE
.NET 7: New problem details service

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26685] opened 2022-08-10 00:59 UTC
[New problem details service](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/#new-problem-details-service)

- [x] Create sample middleware in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware from https://github.com/dotnet/AspNetCore.Docs.Samples/pull/25

Sample at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware/problem-details-service

Also document #25107

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sammychinedu2ky** [comment] 2022-08-14 23:47
Would work on this @Rick-Anderson

**Comment by Rick-Anderson** [comment] 2022-08-15 03:37
Fantastic

**Comment by sammychinedu2ky** [comment] 2022-08-20 08:11
@Rick-Anderson  for some reason the  `problemDetailsService.WriteAsync(new { HttpContext = httpContext });` doesn't accept an anonymous type as they said in the docs and it also doesn't resolve a `ProblemDetailsContext` class due to the fact that it is marked obsolete.
There is also a current issue with the feature https://github.com/dotnet/aspnetcore/issues/43261

**Comment by Rick-Anderson** [comment] 2022-08-22 00:33
> @Rick-Anderson for some reason the `problemDetailsService.WriteAsync(new { HttpContext = httpContext });` doesn't accept an anonymous type as they said in the docs and it also doesn't resolve a `ProblemDetailsContext` class due to the fact that it is marked obsolete. There is also a current issue with the feature [dotnet/aspnetcore#43261](https://github.com/dotnet/aspnetcore/issues/43261)

@brunolins16 please review. When should we start the documentation?

**Comment by brunolins16** [comment] 2022-08-24 17:24
@sammychinedu2ky The issue is related to something different. Can you share your example? I very weird because the `ProblemDetailsContext` should not be marked as obsolete.

**Comment by sammychinedu2ky** [comment] 2022-08-24 17:30
This code below raises the error 
`if (context.RequestServices.GetService<IProblemDetailsService>() is { } problemDetailsService)
{
     problemDetailsService.WriteAsync((new { HttpContext = context }););
}`

The error I get is :
`Argument 1: cannot convert from '<anonymous type: Microsoft.AspNetCore.Http.HttpContext HttpContext>' to 'Microsoft.AspNetCore.Http.ProblemDetailsContext' `

**Comment by brunolins16** [comment] 2022-08-24 17:33
Is there a typo in your comment or it is exactly the code your are using? I am asking because it seems to have some addition parentheses

``` diff
if (context.RequestServices.GetService<IProblemDetailsService>() is { } problemDetailsService) { 
-   problemDetailsService.WriteAsync((new { HttpContext = context }););
+   problemDetailsService.WriteAsync(new { HttpContext = context });
}
```

**Comment by sammychinedu2ky** [comment] 2022-08-24 17:40
ooh sorry, this actually|
`problemDetailsService.WriteAsync(new { HttpContext = context });`

**Comment by brunolins16** [comment] 2022-08-24 17:41
So this code `problemDetailsService.WriteAsync(new { HttpContext = context });` is not compiling? Are you using .NET 7 Preview 7?

**Comment by sammychinedu2ky** [comment] 2022-08-24 17:44
I'm using this @brunolins16  
`Version:   7.0.100-preview.7.22377.5`

**Comment by brunolins16** [comment] 2022-08-24 18:24
@sammychinedu2ky  I just tried, and it looks like some compiler configuration because I can build the same code in _**aspnetcore**_ repo but not outside. However, I was able to build this without the obsolete error warning:

``` c#
problemDetailsService.WriteAsync(new ProblemDetailsContext{ HttpContext = context });
```

**Comment by brunolins16** [comment] 2022-08-24 18:44
@sammychinedu2ky  actually the blog post missed a parentheses, it should be:


``` c#
if (context.RequestServices.GetService<IProblemDetailsService>() is { } problemDetailsService) { 
-   problemDetailsService.WriteAsync(new { HttpContext = context });
+   problemDetailsService.WriteAsync(new (){ HttpContext = context });
}

```

**Comment by sammychinedu2ky** [comment] 2022-08-24 19:07
> @sammychinedu2ky actually the blog post missed a parentheses, it should be:
> 
> ```diff
> if (context.RequestServices.GetService<IProblemDetailsService>() is { } problemDetailsService) { 
> -   problemDetailsService.WriteAsync(new { HttpContext = context });
> +   problemDetailsService.WriteAsync(new (){ HttpContext = context });
> }
> ```
> 
> Sorry about that.

thanks, @brunolins16 .
I tried restarting my system and added the parenthesis. but I still get the error below
`ProblemDetailsContext.ProblemDetailsContext()' is obsolete: 'Constructors of types with required members are not supported in this version of your compiler.' `
Please is there a step I'm missing for the compiler to work properly

**Comment by brunolins16** [comment] 2022-08-24 19:11
Look like it is complaining about the [Required Property](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required). Can you share a simple repro? I can try to understand what you are missing.

**Comment by sammychinedu2ky** [comment] 2022-08-24 19:13
When I check class definition I see this 
`namespace Microsoft.AspNetCore.Http
{
    //
    // Summary:
    //     Represent the current problem details context for the request.
    [RequiredMember]
    public sealed class ProblemDetailsContext
    {
        [CompilerFeatureRequired("RequiredMembers")]
        [Obsolete("Constructors of types with required members are not supported in this version of your compiler.", true)]
        public ProblemDetailsContext();

        //
        // Summary:
        //     The Microsoft.AspNetCore.Http.ProblemDetailsContext.HttpContext associated with
        //     the current request being processed by the filter.
        [RequiredMember]
        public HttpContext HttpContext { get; init; }`

@brunolins16

**Comment by brunolins16** [comment] 2022-08-24 19:14
I think that is expected when the `required` is used.

**Comment by sammychinedu2ky** [comment] 2022-08-24 19:17
> I think that is expected when the `required` is used.

but the constructor is marked as obsolete.

**Comment by brunolins16** [comment] 2022-08-24 19:29
I think the latest compilers handle this.

**Comment by sammychinedu2ky** [comment] 2022-08-24 19:53
> ```cs
> problemDetailsService.WriteAsync(new ProblemDetailsContext{ HttpContext = context });
> ```

alright thanks .. would be waiting for it

**Comment by Rick-Anderson** [comment] 2022-08-24 19:54
@sammychinedu2ky  go with Bruno's recommendation. If you like, create an issue to track this.

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:00
> @sammychinedu2ky go with Bruno's recommendation. If you like, create an issue to track this.

Thanks @Rick-Anderson , I took note of his recommendations but still got the same issue, he said the latest compiler would fix it.

**Comment by brunolins16** [comment] 2022-08-24 20:04
The weird thing is that you should be in the latest compiler version, right? Because i cannot repro here. Can you share your csproj? Or a github Repo?

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:08
here is a sample repo @brunolins16 
https://github.com/sammychinedu2ky/problemdetails.git

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:09
![image](https://user-images.githubusercontent.com/36219292/186513520-6f5739a6-720c-4e7c-a917-c1adb1d0dade.png)

Currently that is the issue I'm having

**Comment by brunolins16** [comment] 2022-08-24 20:24
> here is a sample repo @brunolins16 Bruno Oliveira FTE https://github.com/sammychinedu2ky/problemdetails.git

I cloned your repo and it is building correctly? It looks like you have something misconfigured on your side. Can you try run `dotnet build -bl` and share the `msbuild.binlog` file with me?

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:27
> dotnet build -bl

okay, have made an update , the new recent commit has the msbuild.binlog file https://github.com/sammychinedu2ky/problemdetails.git

**Comment by brunolins16** [comment] 2022-08-24 20:32
@sammychinedu2ky is it building successfully? It that just about the red squiggly?

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:34
ooh I'm sorry it is building successfully, it is just the squiggly sign.

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:35
seems its from Omni sharp. please is there a reference you have for the dotnet build -bl command, as I don't understand what it is for. I could read up and learn about it @brunolins16

**Comment by brunolins16** [comment] 2022-08-24 20:38
Are you using VS Code? Maybe the extensions is not updated yet, not sure about it.

**Comment by brunolins16** [comment] 2022-08-24 20:39
I was not able to find where it is documented but I recommend you look at the MSBuild Log Viewer for help https://msbuildlog.com/

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:41
> Are you using VS Code? Maybe the extensions is not updated yet, not sure about it.

yh I'm using updated extensions in Vscode and my Omnisharp seems not to support it for some reason ( maybe it is using the old compiler)

**Comment by sammychinedu2ky** [comment] 2022-08-24 20:42
> I was not able to find where it is documented but I recommend you look at the MSBuild Log Viewer for help https://msbuildlog.com/

thanks

**Closed** 2022-10-11 01:04 UTC
Labels: doc-idea, 7.0
