### ISSUE TITLE
[Blazor] Expand the contents of the build/replace custom MS

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#26382] opened 2022-07-11 13:58 UTC
[EDIT by guardrex to add the metadata]

# Passing your own provider options

Define a class with the data that you will be passing in to the underlying JavaScript library. 

**Shape must match what your library expects when json serialized with System.Text.Json.**

```csharp
public class MyProviderOptions
{
    public string Authority { get; set; }
    public string MetadataUrl { get; set; }
    [JsonPropertyName("client_id")]
    public string ClientId { get; set; }
    public IList<string> DefaultScopes { get; } = new List<string> { "openid", "profile" };
    [JsonPropertyName("redirect_uri")]
    public string RedirectUri { get; set; }
    [JsonPropertyName("post_logout_redirect_uri")]
    public string PostLogoutRedirectUri { get; set; }
    [JsonPropertyName("response_type")]
    public string ResponseType { get; set; }
    [JsonPropertyName("response_mode")]
    public string ResponseMode { get; set; }
}
```

Register the provider options within the DI system and configure the appropriate values

```csharp
services.AddRemoteAuthentication<RemoteAuthenticationState, RemoteUserAccount, MyProviderOptions>(options => {
    options.Authority = "..."
    options.MetadataUrl = "..."
    options.ClientId = "..."
    options.DefaultScopes = new List<string> { "openid", "profile", "myApi" };
    options.RedirectUri = Uri.Create(builder.BaseUri, "authentication/login-callback");
    options.PostLogoutRedirectUri = Uri.Create(builder.BaseUri, "authentication/logout-callback");
    options.ResponseType = "..."
    options.ResponseMode = "..."
})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c572618c-8b98-95af-6a75-1f8e413071db
* Version Independent ID: 8670b314-460d-3194-c53b-9a44f39c6b2a
* Content: [Secure ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2022-07-11 19:19
Duplicate of #26381.

**Closed by guardrex** 2022-07-11 19:19 UTC
Labels: P1, Blazor, doc-enhancement
