### ISSUE TITLE
About MovieGenreViewModel.SearchString

### ISSUE THREAD

**Issue by mrmowji** [dotnet/AspNetCore.Docs#17964] opened 2020-04-23 10:38 UTC
It seems I've already reported a similar issue (#16526) some time ago :) #17957 is new and I was guided to send a feedback from the page itself rather than submitting a PR.

The problem is that you used the `SearchString` property of `movieGenreVM` inside the view (even though you haven't specified the `Model`), and yet this property is not set in the controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2020-04-23 18:41
Duplicate of #16526

**Closed by Rick-Anderson** 2020-04-23 18:41 UTC
Labels: Source - Docs.ms, doc-enhancement
