### ISSUE TITLE
Swagger or OpenAPI

### ISSUE THREAD

**Issue by Lamothe** [dotnet/AspNetCore.Docs#9902] opened 2018-12-08 05:19 UTC
"OpenAPI is preferred" ... and that's the last time that OpenAPI is mentioned.  It's "Swagger" all the way down.  Just sayin'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34eea37-51a4-6227-f5ed-6501624ad045
* Version Independent ID: 2994cf60-0cb7-afa2-20b8-7e2b1117f964
* Content: [ASP.NET Core Web API help pages with Swagger / OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md)
* Product: **aspnet-core**
* GitHub Login: @RSuter
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment] 2018-12-14 00:32
@scottaddie 	this is fixed in your PR - right?

**Comment by RSuter** [comment] 2018-12-14 07:47
For me personally Swagger is v2 and OpenAPI is v3 (but OpenAPI was also used in the v2 era). So essentially they can be used interchangeably but eventually we should only use OpenAPI - because Swagger is like a propriatery implementation of OpenAPI. The problem is that Swagger is much more known in the community...

**Comment by ppppersy** [comment] 2019-01-31 16:18
good post!

**Comment by osca2000** [comment] 2019-06-28 00:09
Nuget has got Microsoft.OpenAPI and Swagger. For API documentation, can we use Microsoft.OpenAPI only? Without Microsoft.OpenAPI, swagger does all. What is the role of Microsoft.OpenAPI then? I cannot find any sample of Microsoft.OpenAPI to do Swagger UI style documentation. In the past, visual studio api project did all this as default. But not anymore.

**Comment by serpent5** [comment] 2021-12-17 10:56
This was addressed with the [OpenApi vs. Swagger](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-6.0#openapi-vs-swagger) section.

**Closed by serpent5** 2021-12-17 10:56 UTC
Labels: P2, Source - Docs.ms, doc-bug
