### ISSUE TITLE
Client example doesn't compile or work properly on VS for Mac 2022 Preview with .NET 6

### ISSUE THREAD

**Issue by biozal** [dotnet/AspNetCore.Docs#24221] opened 2021-12-07 21:38 UTC
Trying to follow documentation posted here:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio-mac#create-the-grpc-client-in-a-net-console-app

When adding the Grpc.Net.Client nuget package it's not enough.  If you copy over the proto file it will still fail because of the following:

Need a reference to the Grpc.Tools nuget package which is used to auto-generate the code.  the Grpc.Net.Client nuget package doesn't include a requirement for this package so you have to manually add this.

Once you add this and try to build you will get errors about namespace and Google missing.  This is because the Google.Protobuf nuget package is also required.  So in summary:

To get the client working you need the following nuget package references:
Google.Protobuf
Grpc.Net.Client
Grpc.Tools

Once doing this the rest of the code example worked as written.

Thanks
Aaron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment] 2021-12-10 21:43
@biozal,  For the Mac the Nuget Packages you called out are listed there along with instructions for getting them.  See the screenshot below.  Maybe the issue is that it is too easy to miss the required package list at the top and the last instruction of repeating the install steps for all three?  Thanks for your help and insights.
![image](https://user-images.githubusercontent.com/10985336/145644747-6164a7ac-a565-480d-b48b-d8d89635e0fa.png)

**Comment by wadepickett** [comment] 2021-12-10 21:47
I am closing this issue for now but will re-open if there is something I am misunderstanding, and we need to make a change.  See my previous comment.

**Closed by wadepickett** 2021-12-10 21:47 UTC
Labels: P1, Source - Docs.ms, doc-enhancement, gRPC, 6.0 Post GA
