### ISSUE TITLE
OptionalParameter.razor - misleading example for setting default parameter value (OnInitialized vs. OnParametersSet)

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31845] opened 2024-02-16 00:31 UTC
### Description

Although it is not explicitly stated in referring article [Components - Overview: Route parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#route-parameters), the only possible interpretation of the code snippet is that it is trying to set a fallback (default) value for `Text` route parameter in `OnInitialized`.

https://github.com/dotnet/blazor-samples/blob/5ff0fac37cd80233f43ffc8cfb2174cff7ea77bd/8.0/BlazorSample_BlazorWebApp/Components/Pages/OptionalParameter.razor#L1-L13
```razor
@page "/optional-parameter/{text?}"

<h1>Blazor is @Text!</h1>

@code {
    [Parameter]
    public string? Text { get; set; }

    protected override void OnInitialized()
    {
        Text = Text ?? "fantastic";
    }
}
```

I think the usage of `OnInitialized` here is inappropriate and misleading.
Consider this simple repro:
```razor
@page "/optional-parameter/{text?}"

<h1>Blazor is @Text!</h1>

<a href="optional-parameter/great">Great</a><br />
<a href="optional-parameter/">Default</a>

@code {
    [Parameter]
    public string? Text { get; set; }

    protected override void OnInitialized()
    {
        Text = Text ?? "fantastic";
    }
}
```
When you click _Great_, the result is _Blazor is great!_ However, navigating to _Default_ yields _Blazor is !_ since the`OnInitialized` method is not called when the component instance is reused with new parameter values.

![2024-02-16_01-02-18](https://github.com/dotnet/blazor-samples/assets/12828888/b589959f-0f4e-4734-8d56-7278c291435e)

**To provide a good-practice example, we should change the code to use `OnParametersSet` method instead.**

---

Oh, I found another clone of this example in [Fundamentals - Routing and navigation: Route parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#route-parameters) section, the `RouteParameter2.razor` sample.
There, the suboptimal use of `OnInitialized` is addressed with a written explanation on why and when `OnParametersSet` should be used instead. This explanation mirrors the issue I've highlighted. It's unnecessary to provide an example that requires subsequent correction. Instead, we should directly use `OnParametersSet`, possibly with a note clarifying why `OnInitialized` should be avoided.

---

My proposal (I will submit a PR if we agree on the solution):
1. Change the `OptionalParameter.razor` and `RouteParameter2.razor` to use `OnParametersSet` instead of `OnInitialized`.
2. Change `components/index.md` to refer to `OnParametersSet` in text instead of `OnInitialized`.
3. Change `fundamentals/routing.md` and remove the explanation on how to fix the issue `OnParametersSet`.
4. [OPTIONAL] Add an explanation to `fundamentals/routing.md` on why `OnInitialized` should not be used.

--- 

IMHO, the use of `OnInitialized` should be considered narrowly, reserved exclusively for scenarios unaffected by parameter value changes and valid for the entire lifetime of the component INSTANCE. This might include loading static options for dropdowns and other "initializations" not dependent on parameter values (or their changes, respectively).

It seems this nuance is not emphasized enough in the documentation, as I frequently encounter this issue during code reviews. This recurring misunderstanding among developers highlights a gap in the educational materials provided.

Furthermore, the behavior of `OnParametersSet` regarding the detection of parameter changes is another area where developers often lack awareness. It's important to understand that `OnParametersSet` can be invoked, even if the parameter values have not changed. This behavior underscores the need for developers to implement additional logic within `OnParametersSet` to check whether parameter values have indeed changed before re-initializing data or state dependent on those parameters.

(But this relates to another section; here, it's just a lament.)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md

### Document ID

31ad18df-1904-bbdd-cfed-8d0d0267c10e

### Article author

@guardrex

**Comment by guardrex** [comment] 2024-02-16 11:57
I agree that this is a problem and agree with most of your proposal. I think your language describing the severity of the problem is too strong. To me, this is the critical point ...

> reserved exclusively for scenarios unaffected by parameter value changes and valid for the entire lifetime of the component INSTANCE

If that's the spec, then that's what the dev should code for. The text fails to explain the approaches and behavioral differences clearly, and that's the main problem in my mind.

First off ... I'm going to perform a quick patch PR update to the [*Components* node overview article section on *Route parameters*](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#route-parameters). There's a couple of aspects that I don't like about that section that I'd like to fix up. I'll ping back here shortly.

On the rest ...

Let's include (4) of your proposal 👍, but let's phrase it more along the lines of 'this is what will happen if `OnInitialized{Async}` is used'.

🤔 WRT addressing the subject in the *Lifecycle* article as part of this effort, it could go either way. It could be worked on the PR that fixes this issue, or it could be addressed by a separate issue/PR later. If you would like to work that on this issue, let's discuss that here before action is taken on the articles.

Two notes on the sample apps:

* The locations of components changed when the samples went from only supplying snippets to acting as demonstration apps. Fortunately, a search in the repo's folder will turn up the components across the apps (Blazor Server, Blazor WASM, BWA). Optional params came in at 5.0, *so hopefully you won't find a (broken) example in the 3.1 sample apps!* 😄
* Update the sample apps first. The docs build engine draws the code when the article is updated on a PR.

*Stand-by for sec ...................... brb ...........................................*

**Comment by hakenr** [comment] 2024-02-16 13:42
I will try to create PRs for these:
> - Start with the sample apps because the build system draws the code into the docs from that repo ... and please kill 🔪💀 the OptionalParameter component in the process.
> - Include (4) of your proposal 👍, but let's phrase it more along the lines of 'this is what the behavior is if OnInitialized{Async} is used.'

Please create a separate issue for the last one if you agree we should try to address this.
> - Let me know if you want to work on the Lifecycle article with this or if you would like me to open a new issue to address it later. We'd need to discuss changes for that article a bit more, and we can do that here or on a new issue.

**Comment by guardrex** [comment] 2024-02-16 13:43
Very good ... I'll open an issue for the *Lifecycle* article.

**Closed** 2024-02-20 11:52 UTC
Labels: Pri1, Source - Docs.ms, Blazor, doc-enhancement, aspnet-core/svc, blazor/subsvc
