### ISSUE TITLE
ASP.NET Core Blazor forms and validation with Fluent API model

### ISSUE THREAD

**Issue by lenj962** [dotnet/AspNetCore.Docs#18468] opened 2020-05-24 17:43 UTC
I have an existing solution that I would like to move to Blazor where the model uses Entity Framework Core and the Fluent API.  This documentation indicates that only data annotations should be used.  Is there a way to get this model to work with Blazor and use validation?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2020-05-24 17:52
Hello @lenj962 ...

> should be used

Not really "should be" ... it's just that we don't have EF Core coverage specifically for Blazor at this time.

We'll be putting up an EF Core topic for Blazor on https://github.com/dotnet/AspNetCore.Docs/issues/16558, which I would think will demo some Fluent API. It's being handled by the EF Core team, and I'll work on getting the topic up after they're done with a sample app.

For now, we just have some DI concepts covered at https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di.

I'll close this as a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/16558.

**Closed by guardrex** 2020-05-24 17:52 UTC
Labels: :watch: Not Triaged, Blazor, Source - Docs.ms

**Comment by RudyD** [comment] 2023-01-14 20:51
Hi @guardrex - We're coming up on two and a half years now since this item was closed since it was a duplicate of #16558, which, by the way, is also closed, but years later I struggle to find the examples/demos of using Fluent API usage with Blazor. Does this exist? Did the EF Core team ever make this happen?

@lenj962 , did you end up updating your code to use data annotations anyway? Reason I ask is because I'm trying to find easy ways of form validation without involving third-party packages. The examples I see online leverage Data Annotation validation.

**Comment by guardrex** [comment] 2023-01-15 01:08
Yes, a topic+sample is up. @JeremyLikness wrote it and built the sample app, which I just touch-up release-to-release for any breaking changes and new features. The topic is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-7.0

... but it isn't Fluent-based. You can check the sample out at ...

https://github.com/dotnet/blazor-samples/tree/main/7.0/BlazorServerEFCoreSample

You'd need to go to web resources for Fluent with Blazor if there's anything special about implementing Fluent with Blazor. I wouldn't think there are any deal breakers on it. We're just not going to maintain a sample app or content related to Fluent here. However, @JeremyLikness tho is the ***real expert*** in this area ... *I'm just a silly green* 🦖😄, and he may remark on it when he sees this.
