### ISSUE TITLE
Minor issues (bad link, incorrect instructions?)

### ISSUE THREAD

**Issue by marius00** [dotnet/AspNetCore.Docs#22881] opened 2021-07-29 07:27 UTC
**Hosting model**: webassembly

1. The (how to download) link does not take you anywhere that explains how to partially clone a git repo, it takes you to an anchor tag which does not appear to exist.
2. There is no new project type called "Blazor App", its blazor webassembly or server
3. After creating the client (as there was no "make both" option in the start), the rest of the tutorial assumes another project named "BlazorWebAssemblySignalRApp.Server" has magically appeared.
4. A quick introduction in as to how the flow/logic will be would be nice, before jumping into the code, so you can see where you're going.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2021-07-29 11:12
Hello @marius00 ...

1. It's in the middle of the page: scroll UP after the page loads. It didn't load the page with the section in view. I've seen this happen, too. Actually, it happens to me frequently enough that the docs team should be asked to take a look. I opened https://github.com/MicrosoftDocs/feedback/issues/3667 to see what they say. If they can reproduce the problem themselves, they'll take it up as a 🐞 bug to fix. If they can't repro it tho, they'll close it probably as some sort of rare browser quirk. For example, I tried in Edge, and the page did load to the *How to download a sample* section.

1. **_Yep!_ They moved the 🧀 on it!** Visual Studio is a whole different team. They change the UI from time-to-time, and so docs will break. I'll take care of this right now. I'll make it more generic because many readers might not have the latest version of VS; therefore, they'll see what the current doc describes. This is a change will be made across several Blazor docs that speak to creating a new Blazor app in VS.

1. **_Indeed!_** ... another VS delta for the latest VS release. They've moved the checkbox for **ASP.NET Core hosted** from the **Advanced** area of one screen to the new **Additional information** screen. I'll take care of this. This also will need to be made more generic in the topic because many might be on an older version of VS. This is also a change that I'll be making to several Blazor docs.

1. That's actually counter to management's decision (docs team) on how tutorials are written. They intend for you to learn by getting right into the code for a quick successful experience. They want to leave the theory, additional configuration, gotchas, cross-links, etc. to the reference topics. After the tutorial, it links off to the reference docs in the **Next steps** section at the bottom.

Thanks for writing in on the VS situation. I'll take care of it immediately.

**Comment by marius00** [comment] 2021-07-29 11:20
1. You were correct in your assessment of me using Firefox.
2/3. After a lot of fighting between was VS gave me and trying to make the example itself compile, I found the checkbox. The tooltip could be a bit more descriptive (but that's a VS issue). 
4. Ah, scratch that then.

I honestly expect this to go into /dev/null, so thanks for the feedback!

**Closed** 2021-07-29 12:03 UTC
Labels: Blazor, P0, SignalR, Source - Docs.ms, doc-bug

**Comment by guardrex** [comment] 2021-07-29 12:11
I just merged the PR to at least temporarily patch it up. I'll take that update live immediately, so it should show up on the live docs site in 10-20 minutes.

I've also reached out to management to see if they'd like to take another approach (e.g., break it out by version).

> but that's a VS issue

Yes ... use the **Suggest a Feature** process from within VS ...

https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019

That process opens an internal issue for the VS team. Our management does interact with them quite a bit tho. I referenced this issue in my internal message. If they like the idea of providing more info in the VS portal for the hosted solution checkbox, they may take it up internally with them. Still tho ... you probably should use the **Suggest a Feature** process. That's the best bet.

WRT FF and that bookmark problem, I have seen that here. Let's see if they can repro it using this exact doc. Hopefully, it's a reproducible bug for them. They **_will_** address it if so. My fear is that it's some sort of wildly intermittent edge case for some (probably FF) users and some topics and they can't repro it ... they will just close that issue saying it's too rare to work on. We'll see.
